import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8");
// Gate 2 — aprobación dual
test("aprobación dual impide autoaprobación",()=>{const s=read("supabase/migrations/20260720001000_p2_madurez_operativa.sql");assert.match(s,/aprobada_por <> solicitada_por/);assert.match(s,/APROBADOR_DEBE_SER_DISTINTO/);assert.match(s,/for update/);});
test("capacidades granulares pueden conceder o revocar",()=>{const s=read("supabase/migrations/20260720001000_p2_madurez_operativa.sql");assert.match(s,/admin_capacidades/);assert.match(s,/coalesce\(\(select ac\.concedida/);});
// Gate 1 — exportación limitada, neutralizada y trazada
test("exportación queda limitada, neutralizada y trazada",()=>{const route=read("apps/panel-admin/src/app/api/exportaciones/pagos/route.ts");const servicio=read("packages/api/src/operations/exports.ts");assert.match(route,/LIMITE_FILAS=10_000/);assert.match(route,/\^\[=\+\\-@\]/);assert.match(route,/sha256/);assert.match(route,/completarExportacionAdmin/);assert.match(servicio,/admin_completar_exportacion/);});
test("dashboard de auditoría usa API route paginada",()=>{const s=read("apps/panel-admin/src/app/auditoria/page.tsx");assert.match(s,/\/api\/auditoria/);assert.match(s,/paginacion/);assert.match(s,/totalPages/);});
test("API de auditoría verifica permisos y pagina resultados",()=>{const route=read("apps/panel-admin/src/app/api/auditoria/route.ts");const consulta=read("packages/api/src/operations/queries/auditoria-seguridad.ts");const permisos=read("packages/api/src/services/permisos-admin.ts");assert.match(route,/tienePermisoAdmin/);assert.match(route,/auditoria:leer/);assert.match(consulta,/assertAdminPermission\(cliente, "auditoria:leer"\)/);assert.match(consulta,/\.range\(/);assert.match(consulta,/count:.*exact/);assert.match(permisos,/admin_tiene_permiso/);assert.match(route,/CAMPOS_SENSIBLES_VISUALIZACION/);});
// Sprint 1 — bypass cerrar
test("operaciones sensibles exigen aprobación dual válida en SQL",()=>{const s=read("supabase/migrations/20260720001200_sprint1_bypass_cerrar.sql");assert.match(s,/admin_validar_aprobacion/);assert.match(s,/admin_ejecutar_aprobacion/);assert.match(s,/admin_ajustar_precio_final/);assert.match(s,/admin_ejecutar_pago/);assert.match(s,/admin_suspender_conductor/);assert.match(s,/admin_registrar_no_presentacion/);assert.match(s,/admin_registrar_cancelacion_injustificada/);assert.match(s,/APROBACION_PAYLOAD_NO_COINCIDE/);assert.match(s,/APROBACION_REQUERIDA/);});
test("servicios TypeScript migrados a RPC y bloquean estados críticos",()=>{const s=[read("packages/api/src/billing/pagos.ts"),read("packages/api/src/drivers/conductores.ts"),read("packages/api/src/transfers/operativa.ts")].join("\n");assert.match(s,/admin_ajustar_precio_final/);assert.match(s,/admin_suspender_conductor/);assert.match(s,/admin_registrar_no_presentacion/);assert.match(s,/admin_registrar_cancelacion_injustificada/);assert.match(s,/ESTADOS_CRITICOS_TRASLADO/);});
// Sprint 2 — permisos efectivos
test("migración incluye pagos:exportar en matriz de admin_tiene_permiso",()=>{const s=read("supabase/migrations/20260722001300_sprint2_permisos_efectivos.sql");assert.match(s,/pagos:exportar/);assert.match(s,/admin_conceder_capacidad/);assert.match(s,/admin_listar_capacidades_catalogo/);assert.match(s,/admin_listar_capacidades/);assert.match(s,/NO_PUEDES_OTORGARTE_CAPACIDADES_ADMINISTRAR/);assert.match(s,/MOTIVO_OBLIGATORIO/);});
test("RLS policies reemplazan es_admin con admin_tiene_permiso",()=>{const s=read("supabase/migrations/20260722001300_sprint2_permisos_efectivos.sql");assert.match(s,/drop policy if exists admin_acceso_total_pagos/);assert.match(s,/drop policy if exists admin_acceso_total_conductores/);assert.match(s,/admin_tiene_permiso\('pagos:leer'\)/);assert.match(s,/admin_tiene_permiso\('conductores:leer'\)/);});
test("rollo-admin.ts: RUTA_A_CAPACIDAD y obtenerCapacidadParaRuta",()=>{const s=read("apps/panel-admin/src/lib/roles-admin.ts");assert.match(s,/RUTA_A_CAPACIDAD/);assert.match(s,/obtenerCapacidadParaRuta/);assert.match(s,/PermisoAdmin/);assert.match(s,/capacidades:administrar/);});
test("Dirección es superadministrador de rutas y capacidades",()=>{const rutas=read("apps/panel-admin/src/lib/roles-admin.ts");const sql=read("supabase/migrations/20260722001400_direccion_superadmin.sql");assert.match(rutas,/rol === "direccion"/);assert.match(sql,/rol_operativo = 'direccion'\) then true/);assert.match(sql,/v_rol_objetivo <> 'direccion'/);});
test("middleware verifica capacidad efectiva via admin_tiene_permiso",()=>{const middleware=read("apps/panel-admin/src/middleware.ts");const guard=read("packages/api/src/operations/queries/guard-admin.ts");assert.match(middleware,/obtenerCapacidadParaRuta/);assert.match(middleware,/verificarPermisoRuta/);assert.match(guard,/admin_tiene_permiso/);assert.match(middleware,/capacidad_insuficiente/);});
test("exportación endurecida: pagos:exportar, filtros reales, rango fechas",()=>{const s=read("apps/panel-admin/src/app/api/exportaciones/pagos/route.ts");assert.match(s,/pagos:exportar/);assert.match(s,/DIAS_MAX=90/);assert.match(s,/pagos:leer/);assert.match(s,/export_audit_failed/);});
test("permisos-admin.ts incluye pagos:exportar",()=>{const s=read("packages/api/src/services/permisos-admin.ts");assert.match(s,/pagos:exportar/);assert.match(s,/finanzas/);assert.match(s,/direccion/);});
test("existe servicio admin-capacidades.ts y se exporta",()=>{const s=read("packages/api/src/services/admin-capacidades.ts");assert.match(s,/listarCatalogoCapacidades/);assert.match(s,/listarCapacidadesAdmin/);assert.match(s,/concederCapacidadAdmin/);});
test("index de servicios exporta admin-capacidades",()=>{const s=read("packages/api/src/services/index.ts");assert.match(s,/admin-capacidades/);});
test("existe página de gestión de capacidades",()=>{assert.ok(fs.existsSync("apps/panel-admin/src/app/capacidades/page.tsx"));const s=read("apps/panel-admin/src/app/capacidades/page.tsx");assert.match(s,/listarCatalogoCapacidades/);assert.match(s,/concederCapacidadAdmin/);assert.match(s,/capacidades:administrar/);});
test("carga y accesibilidad con sesión real",()=>{assert.ok(fs.existsSync("tests/load/panel-admin-degradacion.js"));const s=read("apps/panel-admin/tests/a11y-real/auditoria-sesiones.spec.ts");assert.match(s,/ADMIN_STORAGE_STATE/);assert.match(s,/AxeBuilder/);});
// P2 — Vehículos: escalabilidad y calidad
test("Vehículos usa paginación backend y búsqueda SQL",()=>{const sql=read("supabase/migrations/20260723001100_p2_vehiculos_escalabilidad_calidad.sql");const svc=read("packages/api/src/vehicles/vehiculos.ts");assert.match(sql,/admin_listar_vehiculos_paginados/);assert.match(sql,/limit v_tamano offset v_offset/);assert.match(sql,/vehiculos:leer/);assert.match(sql,/u\.correo_facturacion ilike/);assert.match(svc,/listarVehiculosAdminPaginados/);});
test("pantalla Vehículos aplica debounce y ya no filtra todo en cliente",()=>{const s=read("apps/panel-admin/src/app/vehiculos/page.tsx");assert.match(s,/busquedaInput/);assert.match(s,/setTimeout\(\(\) =>/);assert.match(s,/listarVehiculosAdminPaginados/);assert.match(s,/TAMANO_PAGINA = 25/);assert.match(s,/Página \{totalPaginas === 0/);assert.doesNotMatch(s,/datos\.vehiculos\.filter/);});
test("dominio de Vehículos valida formato, consistencia documental y concurrencia",()=>{const s=read("packages/api/src/vehicles/vehiculos.ts");assert.match(s,/validarDominioVehiculoAdmin/);assert.match(s,/Clasificación tarifaria incompleta/);assert.match(s,/No puede circular rodando sin/);assert.match(s,/CONCURRENCY_CONFLICT/);assert.match(s,/validarVinYPlacasUnicos/);});
test("exportación de Vehículos es limitada, firmada y auditable",()=>{const route=read("apps/panel-admin/src/app/api/exportaciones/vehiculos/route.ts");const servicio=read("packages/api/src/operations/exports.ts");assert.match(route,/LIMITE_FILAS = 10_000/);assert.match(route,/\^\[=\+\\-@\]/);assert.match(route,/sha256/);assert.match(route,/x-content-sha256/);assert.match(route,/registrarExportacionAdmin/);assert.match(route,/completarExportacionAdmin/);assert.match(servicio,/admin_registrar_exportacion/);assert.match(servicio,/admin_completar_exportacion/);assert.match(route,/export_audit_failed/);});
test("E2E por rol cubre acceso a Vehículos",()=>{const s=read("apps/panel-admin/tests/e2e/roles-acceso.spec.ts");assert.match(s,/Rol: \$\{rol\.rol\}/);assert.match(s,/storageState-operador\.json/);assert.match(s,/storageState-compliance\.json/);assert.match(s,/\"\/vehiculos\"/);assert.doesNotMatch(s,/capaciades/);});
