-- RT-13 — Tarifa automática al usuario (elimina el presupuesto adivinado por
-- el usuario y la clasificación manual de categoría/gama/condición como paso
-- obligatorio; el sistema calcula y muestra la tarifa final directamente).
--
-- No se tocan los 32 estados del traslado ni el flujo de cotización/aceptación
-- (documentacion_* -> cotizacion_generada -> cotizacion_aceptada) -- ese
-- pipeline sigue existiendo para la revisión documental. Lo que cambia es
-- CÓMO se llena precio_cotizado: antes lo tecleaba un admin a mano vía
-- admin_emite_cotizacion; ahora se calcula automáticamente con la fórmula
-- (calcular_tarifa_traslado) desde el momento en que se crea la solicitud,
-- usando: (a) categoría/gama autoasignadas por catálogo marca+modelo,
-- (b) condición = 'seminueva' por default (única variable sin dato objetivo
-- disponible al momento de la solicitud), (c) distancia/tiempo de Mapbox ya
-- capturados por el cliente, (d) horario/día derivados de la fecha/hora.
--
-- admin_emite_cotizacion se conserva intacto como mecanismo de EXCEPCIÓN:
-- si el vehículo no está en el catálogo (o su combinación marca/modelo es
-- ambigua en el Excel fuente), la solicitud queda sin precio_cotizado y
-- Torre de Control la cotiza a mano como hasta ahora.

create extension if not exists unaccent;

-- Catálogo marca/modelo -> categoría de tarifa + gama, para autoasignación.
-- Espejo en base de datos del JSON de packages/shared (fuente: RT-11), para
-- que la clasificación se calcule en un contexto de confianza (función
-- security definer) y no pueda ser declarada por el propio usuario -- ese
-- fue el motivo original por el que esta clasificación vivía solo con Torre
-- de Control.
create table public.catalogo_vehiculos_tarifa (
  id                uuid primary key default gen_random_uuid(),
  marca             text not null,
  modelo            text not null,
  categoria_tarifa  public.categoria_tarifa_vehiculo not null,
  gama              public.gama_vehiculo not null
);

-- Sin índice funcional sobre lower(unaccent(...)): unaccent() es STABLE, no
-- IMMUTABLE, así que Postgres rechaza indexarla directamente. La tabla tiene
-- ~1,365 filas -- un table scan en cada búsqueda por marca/modelo es
-- insignificante, así que no vale la pena envolverla en una función IMMUTABLE
-- solo para poder indexarla.
create index catalogo_vehiculos_tarifa_marca_idx on public.catalogo_vehiculos_tarifa (marca);

comment on table public.catalogo_vehiculos_tarifa is
  'Fuente: Vehiculos_Clasificacion_ruum_corregido.xlsx (misma fuente que packages/shared/src/data/vehiculos-clasificacion.json). Un mismo marca/modelo puede tener más de una fila cuando el Excel original trae variantes con clasificación distinta -- en ese caso catalogar_vehiculo_para_tarifa() no autoasigna (ambigüedad -> revisión manual de Torre de Control).';

alter table public.catalogo_vehiculos_tarifa enable row level security;
create policy "admin_lee_catalogo_vehiculos_tarifa" on public.catalogo_vehiculos_tarifa for select using (public.es_admin());
-- Sin policy de insert/update/delete para ningún rol de app: este catálogo se
-- carga por migración, igual que las tablas de tarifas_*.

insert into public.catalogo_vehiculos_tarifa (marca, modelo, categoria_tarifa, gama) values
('Porsche', 'Panamera', 'ligero_a', 'alta'),
('Porsche', 'Taycan', 'ligero_a', 'alta'),
('Acura', 'Tsx 3.5l', 'ligero_a', 'alta'),
('Acura', 'ILX', 'ligero_a', 'alta'),
('Acura', 'INTEGRA', 'ligero_a', 'alta'),
('Acura', 'TLX', 'ligero_a', 'alta'),
('Acura', 'Tl 3.5l', 'ligero_a', 'alta'),
('Acura', 'Tl 3.7l', 'ligero_a', 'alta'),
('Acura', 'Rl', 'ligero_a', 'alta'),
('Acura', 'Rlx', 'ligero_a', 'alta'),
('Acura', 'TSX 2.4L', 'ligero_a', 'alta'),
('Alfa Romeo', '4C', 'ligero_a', 'alta'),
('Alfa Romeo', 'Alfa Romeo 159 2.2 Jts Sport Plus Selespeed', 'ligero_a', 'alta'),
('Alfa Romeo', 'Alfa Romeo 159 3.2 Sport Plus Awd Automatico', 'ligero_a', 'alta'),
('Alfa Romeo', 'Giulia', 'ligero_a', 'alta'),
('Alfa Romeo', 'Stelvio', 'ligero_a', 'alta'),
('Alfa Romeo', 'Alfa Romeo Mito Quadrifoglio Verde Manual', 'ligero_a', 'alta'),
('Alfa Romeo', 'Alfa Romeo Giulietta Progression Manual', 'ligero_a', 'alta'),
('Audi', 'A 1 1.4T', 'ligero_a', 'alta'),
('Audi', 'A1', 'ligero_a', 'alta'),
('Audi', 'A3 Sedán', 'ligero_a', 'alta'),
('Audi', 'A3-', 'ligero_a', 'alta'),
('Audi', 'A4', 'ligero_a', 'alta'),
('Audi', 'A4 1.8 Cabrio', 'ligero_a', 'alta'),
('Audi', 'A4 1.8T', 'ligero_a', 'alta'),
('Audi', 'A4 2.0', 'ligero_a', 'alta'),
('Audi', 'A4 2.0 Cabrio', 'ligero_a', 'alta'),
('Audi', 'A4 3.0', 'ligero_a', 'alta'),
('Audi', 'A4 3.0 Cabrio', 'ligero_a', 'alta'),
('Audi', 'A4 3.2', 'ligero_a', 'alta'),
('Audi', 'A5', 'ligero_a', 'alta'),
('Audi', 'A5 2.0', 'ligero_a', 'alta'),
('Audi', 'A5 3.2', 'ligero_a', 'alta'),
('Audi', 'A5 Cabrio', 'ligero_a', 'alta'),
('Audi', 'A5 Coupe', 'ligero_a', 'alta'),
('Audi', 'A5 Sedán', 'ligero_a', 'alta'),
('Audi', 'A6', 'ligero_a', 'alta'),
('Audi', 'A6 2.7 Biturbo', 'ligero_a', 'alta'),
('Audi', 'A6 2.8', 'ligero_a', 'alta'),
('Audi', 'A6 3.0', 'ligero_a', 'alta'),
('Audi', 'A6 3.2', 'ligero_a', 'alta'),
('Audi', 'A6 4.2', 'ligero_a', 'alta'),
('Audi', 'A7', 'ligero_a', 'alta'),
('Audi', 'A8', 'ligero_a', 'alta'),
('Audi', 'A8 4.2', 'ligero_a', 'alta'),
('Audi', 'Q6 etron', 'ligero_a', 'alta'),
('Audi', 'R8', 'ligero_a', 'alta'),
('Audi', 'R8 Spyder', 'ligero_a', 'alta'),
('Audi', 'RS 6', 'ligero_a', 'alta'),
('Audi', 'RS4 4.2', 'ligero_a', 'alta'),
('Audi', 'RS5 4.2', 'ligero_a', 'alta'),
('Audi', 'RS6 Avant', 'ligero_a', 'alta'),
('Audi', 'RS6 Sedan', 'ligero_a', 'alta'),
('Audi', 'S3 2.0', 'ligero_a', 'alta'),
('Audi', 'S4 3.0', 'ligero_a', 'alta'),
('Audi', 'S4 4.2', 'ligero_a', 'alta'),
('Audi', 'S5 4.2', 'ligero_a', 'alta'),
('Audi', 'S6', 'ligero_a', 'alta'),
('Audi', 'S8', 'ligero_a', 'alta'),
('Audi', 'Sportback', 'ligero_a', 'alta'),
('Audi', 'TTRS Coupe', 'ligero_a', 'alta'),
('Audi', 'TTS Coupe', 'ligero_a', 'alta'),
('Audi', 'TTS Roadster', 'ligero_a', 'alta'),
('Audi', 'S4 4.2 Cabrio', 'ligero_a', 'alta'),
('Audi', 'A1-', 'ligero_a', 'alta'),
('Audi', 'A3', 'ligero_a', 'alta'),
('Audi', 'Q2', 'ligero_a', 'alta'),
('Audi', 'A1*', 'ligero_a', 'alta'),
('Audi', 'A3 Cabrio', 'ligero_a', 'alta'),
('Audi', 'Q3', 'ligero_a', 'alta'),
('Audi', 'TT Coupe', 'ligero_a', 'alta'),
('Audi', 'TT Roadster', 'ligero_a', 'alta'),
('Audi', 'A5 2.0T Sportback', 'ligero_a', 'alta'),
('Audi', 'A5 3.2 Sportback', 'ligero_a', 'alta'),
('Audi', 'A5 Sportback', 'ligero_a', 'alta'),
('Bentley', 'Arnage R', 'ligero_a', 'alta'),
('Bentley', 'Azure', 'ligero_a', 'alta'),
('Bentley', 'Bentayga', 'ligero_a', 'alta'),
('Bentley', 'Continental', 'ligero_a', 'alta'),
('Bentley', 'Flying Spur', 'ligero_a', 'alta'),
('Bentley', 'Mulsanne', 'ligero_a', 'alta'),
('BMW', 'Serie 3-', 'ligero_a', 'alta'),
('BMW', '118I', 'ligero_a', 'alta'),
('BMW', '120I', 'ligero_a', 'alta'),
('BMW', '120i 3p', 'ligero_a', 'alta'),
('BMW', '125i Coupe', 'ligero_a', 'alta'),
('BMW', '130I', 'ligero_a', 'alta'),
('BMW', '130i 3p', 'ligero_a', 'alta'),
('BMW', '135i Coupe', 'ligero_a', 'alta'),
('BMW', '320I', 'ligero_a', 'alta'),
('BMW', '325CI', 'ligero_a', 'alta'),
('BMW', '325CI Cabrio', 'ligero_a', 'alta'),
('BMW', '325I', 'ligero_a', 'alta'),
('BMW', '325I SDK', 'ligero_a', 'alta'),
('BMW', '325i Cabrio', 'ligero_a', 'alta'),
('BMW', '325i Coupe', 'ligero_a', 'alta'),
('BMW', '330CI', 'ligero_a', 'alta'),
('BMW', '330CI Cabrio', 'ligero_a', 'alta'),
('BMW', '330I', 'ligero_a', 'alta'),
('BMW', '335i', 'ligero_a', 'alta'),
('BMW', '335i Cabrio', 'ligero_a', 'alta'),
('BMW', '335i Coupe', 'ligero_a', 'alta'),
('BMW', '525I', 'ligero_a', 'alta'),
('BMW', '528I', 'ligero_a', 'alta'),
('BMW', '530I', 'ligero_a', 'alta'),
('BMW', '535I', 'ligero_a', 'alta'),
('BMW', '535i Gran Turismo', 'ligero_a', 'alta'),
('BMW', '540I', 'ligero_a', 'alta'),
('BMW', '545I', 'ligero_a', 'alta'),
('BMW', '550I', 'ligero_a', 'alta'),
('BMW', '550i Gran Turismo', 'ligero_a', 'alta'),
('BMW', '645CI', 'ligero_a', 'alta'),
('BMW', '645CI Cabrio', 'ligero_a', 'alta'),
('BMW', '650I', 'ligero_a', 'alta'),
('BMW', '650i Cabrio', 'ligero_a', 'alta'),
('BMW', '740I', 'ligero_a', 'alta'),
('BMW', '745I', 'ligero_a', 'alta'),
('BMW', '750I', 'ligero_a', 'alta'),
('BMW', '760LI', 'ligero_a', 'alta'),
('BMW', 'M3', 'ligero_a', 'alta'),
('BMW', 'M3 Cabrio', 'ligero_a', 'alta'),
('BMW', 'M3 Sedan', 'ligero_a', 'alta'),
('BMW', 'M5', 'ligero_a', 'alta'),
('BMW', 'M6', 'ligero_a', 'alta'),
('BMW', 'Serie 1 Hatch', 'ligero_a', 'alta'),
('BMW', 'Serie 1 M Coupe', 'ligero_a', 'alta'),
('BMW', 'Serie 1 Sedán', 'ligero_a', 'alta'),
('BMW', 'Serie 2', 'ligero_a', 'alta'),
('BMW', 'Serie 3', 'ligero_a', 'alta'),
('BMW', 'Serie 4', 'ligero_a', 'alta'),
('BMW', 'Serie 5', 'ligero_a', 'alta'),
('BMW', 'Serie 6', 'ligero_a', 'alta'),
('BMW', 'Serie 7', 'ligero_a', 'alta'),
('BMW', 'Serie 8', 'ligero_a', 'alta'),
('BMW', 'X1 Sdrive20i', 'ligero_a', 'alta'),
('BMW', 'X1 Xdrive25i', 'ligero_a', 'alta'),
('BMW', 'Z4-', 'ligero_a', 'alta'),
('BMW', 'i3', 'ligero_a', 'alta'),
('BMW', 'i4', 'ligero_a', 'alta'),
('BMW', 'i5', 'ligero_a', 'alta'),
('BMW', 'i7', 'ligero_a', 'alta'),
('BMW', 'iX1', 'ligero_a', 'alta'),
('BMW', 'X1 Xdrive 28i', 'ligero_a', 'alta'),
('BMW', 'XM', 'ligero_a', 'alta'),
('BMW', 'Z4', 'ligero_a', 'alta'),
('BMW', 'i8', 'ligero_a', 'alta'),
('Chirey', 'Arrizo 8', 'ligero_a', 'alta'),
('Chrysler', 'CHRYSLER 300C', 'ligero_a', 'alta'),
('Chrysler', 'Charger', 'ligero_a', 'alta'),
('Chrysler', 'Chrysler 300', 'ligero_a', 'alta'),
('Chrysler', 'Chrysler 200', 'ligero_a', 'alta'),
('Chrysler', 'Crossfire', 'ligero_a', 'alta'),
('Chrysler', 'Challenger', 'ligero_a', 'alta'),
('Chrysler', 'Viper', 'ligero_a', 'alta'),
('Fiat', '124 Spider', 'ligero_a', 'alta'),
('Fiat', '500X', 'ligero_a', 'alta'),
('Fiat', 'Stilo', 'ligero_a', 'alta'),
('Ford Motor', 'Crown Victoria / Police Interceptor', 'ligero_a', 'alta'),
('Ford Motor', 'Five Hundred', 'ligero_a', 'alta'),
('Ford Motor', 'Sable', 'ligero_a', 'alta'),
('Ford Motor', 'Ford GT', 'ligero_a', 'alta'),
('General Motors', 'Regal', 'ligero_a', 'alta'),
('General Motors', 'Ats 4p', 'ligero_a', 'alta'),
('General Motors', 'Cts 2 Ptas', 'ligero_a', 'alta'),
('General Motors', 'Cts 4 Ptas', 'ligero_a', 'alta'),
('General Motors', 'De Ville 4 Ptas', 'ligero_a', 'alta'),
('General Motors', 'Impala', 'ligero_a', 'alta'),
('General Motors', 'Lacrosse', 'ligero_a', 'alta'),
('General Motors', 'Sts 4 Ptas', 'ligero_a', 'alta'),
('General Motors', 'Verano', 'ligero_a', 'alta'),
('General Motors', '147', 'ligero_a', 'alta'),
('General Motors', '156', 'ligero_a', 'alta'),
('General Motors', '9-3 Sport Sedan 4 Ptas', 'ligero_a', 'alta'),
('General Motors', '9-5 4 Ptas', 'ligero_a', 'alta'),
('General Motors', 'Bls 4 Ptas', 'ligero_a', 'alta'),
('General Motors', 'Solstice 2 Ptas', 'ligero_a', 'alta'),
('General Motors', 'Xlr 2 Ptas', 'ligero_a', 'alta'),
('Honda', 'Accord', 'ligero_a', 'alta'),
('Honda', 'Accord', 'ligero_a', 'alta'),
('Honda', 'Accord 2pts', 'ligero_a', 'alta'),
('Honda', 'Accord-', 'ligero_a', 'alta'),
('Honda', 'Crosstour', 'ligero_a', 'alta'),
('Honda', 'Prelude', 'ligero_a', 'alta'),
('Hyundai', 'Genesis', 'ligero_a', 'alta'),
('Hyundai', 'Veloster', 'ligero_a', 'alta'),
('Infiniti', 'G37 Coupe', 'ligero_a', 'alta'),
('Infiniti', 'G37 Sedan', 'ligero_a', 'alta'),
('Infiniti', 'Infiniti', 'ligero_a', 'alta'),
('Infiniti', 'M', 'ligero_a', 'alta'),
('Infiniti', 'Q50', 'ligero_a', 'alta'),
('Infiniti', 'Q60', 'ligero_a', 'alta'),
('Infiniti', 'Q70', 'ligero_a', 'alta'),
('Infiniti', 'QX30', 'ligero_a', 'alta'),
('Jaguar', 'E-Pace', 'ligero_a', 'alta'),
('Jaguar', 'F Type', 'ligero_a', 'alta'),
('Jaguar', 'F-Pace', 'ligero_a', 'alta'),
('Jaguar', 'I-Pace', 'ligero_a', 'alta'),
('Jaguar', 'S Type 3.0l', 'ligero_a', 'alta'),
('Jaguar', 'S Type 4.2l', 'ligero_a', 'alta'),
('Jaguar', 'X Type 2.5l', 'ligero_a', 'alta'),
('Jaguar', 'X Type 3.0l', 'ligero_a', 'alta'),
('Jaguar', 'XE', 'ligero_a', 'alta'),
('Jaguar', 'XF', 'ligero_a', 'alta'),
('Jaguar', 'XF 4.2L', 'ligero_a', 'alta'),
('Jaguar', 'XF 5.0L', 'ligero_a', 'alta'),
('Jaguar', 'XJ', 'ligero_a', 'alta'),
('Jaguar', 'XK', 'ligero_a', 'alta'),
('Jaguar', 'Xj Sedan Series', 'ligero_a', 'alta'),
('Jaguar', 'F-Type', 'ligero_a', 'alta'),
('Jaguar', 'Xk Series', 'ligero_a', 'alta'),
('KIA', 'Stinger', 'ligero_a', 'alta'),
('KIA', 'KIA Óptima', 'ligero_a', 'alta'),
('Land Rover', 'Discovery', 'ligero_a', 'alta'),
('Land Rover', 'Discovery Sport', 'ligero_a', 'alta'),
('Land Rover', 'Range Rover', 'ligero_a', 'alta'),
('Land Rover', 'Range Rover Evoque', 'ligero_a', 'alta'),
('Land Rover', 'Range Rover Velar', 'ligero_a', 'alta'),
('Lexus', 'ES', 'ligero_a', 'alta'),
('Lexus', 'IS', 'ligero_a', 'alta'),
('Lexus', 'LC', 'ligero_a', 'alta'),
('Lexus', 'LS', 'ligero_a', 'alta'),
('Lincoln', 'MKZ Hibrido', 'ligero_a', 'alta'),
('Lincoln', 'MKZ-', 'ligero_a', 'alta'),
('Lincoln', 'Town Car', 'ligero_a', 'alta'),
('Lincoln', 'Lincoln Continental', 'ligero_a', 'alta'),
('Lincoln', 'Lincoln Ls', 'ligero_a', 'alta'),
('Lincoln', 'MKZ', 'ligero_a', 'alta'),
('Lincoln', 'Milan', 'ligero_a', 'alta'),
('Lincoln', 'Mks', 'ligero_a', 'alta'),
('Lincoln', 'Montego', 'ligero_a', 'alta'),
('Lincoln', 'NAUTILUS', 'ligero_a', 'alta'),
('Lynk&Co', '01', 'ligero_a', 'alta'),
('Lynk&Co', '02', 'ligero_a', 'alta'),
('Lynk&Co', '08', 'ligero_a', 'alta'),
('Lynk&Co', '09', 'ligero_a', 'alta'),
('Mazda', 'Mazda 6', 'ligero_a', 'alta'),
('Mazda', 'Mx-5', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 200 K', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 230 K', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 280', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 320', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 350', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 55 Amg', 'ligero_a', 'alta'),
('Mercedes Benz', 'C 63 Amg', 'ligero_a', 'alta'),
('Mercedes Benz', 'CLE', 'ligero_a', 'alta'),
('Mercedes Benz', 'CLS', 'ligero_a', 'alta'),
('Mercedes Benz', 'Cl 230 K', 'ligero_a', 'alta'),
('Mercedes Benz', 'Cl 500', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase A Sedan', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase A hatchback', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase B', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase C 250 Coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase C 350 Coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase C Sedan', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase C coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase E coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase E sedan', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase S coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase S sedan', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clase SL', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 280', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 280 C', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 320', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 320 C', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 350', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 350 C', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 500', 'ligero_a', 'alta'),
('Mercedes Benz', 'Clk 500 C', 'ligero_a', 'alta'),
('Mercedes Benz', 'Cls 350', 'ligero_a', 'alta'),
('Mercedes Benz', 'Cls 500', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 250 Coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 280', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 350', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 350 Convertible', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 350 Coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 500', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 500 Convertible', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 500 Coupe', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 55 Amg', 'ligero_a', 'alta'),
('Mercedes Benz', 'E 63 Amg', 'ligero_a', 'alta'),
('Mercedes Benz', 'E250', 'ligero_a', 'alta'),
('Mercedes Benz', 'EQE', 'ligero_a', 'alta'),
('Mercedes Benz', 'EQS', 'ligero_a', 'alta'),
('Mercedes Benz', 'S 430', 'ligero_a', 'alta'),
('Mercedes Benz', 'S 500', 'ligero_a', 'alta'),
('Mercedes Benz', 'SLC', 'ligero_a', 'alta'),
('Mercedes Benz', 'Sl 500', 'ligero_a', 'alta'),
('Mercedes Benz', 'Sl 55 Amg', 'ligero_a', 'alta'),
('Mercedes Benz', 'Slk 200 K', 'ligero_a', 'alta'),
('Mercedes Benz', 'Slk 350', 'ligero_a', 'alta'),
('Mercedes Benz', 'Sls Amg', 'ligero_a', 'alta'),
('Mercedes Benz', 'A 190', 'ligero_a', 'alta'),
('Mercedes Benz', 'CLA', 'ligero_a', 'alta'),
('MG Motor', 'MG7', 'ligero_a', 'alta'),
('MG Motor', 'CYBERSTER', 'ligero_a', 'alta'),
('MG ROVER', 'Mg Tf', 'ligero_a', 'alta'),
('MG ROVER', 'Mg Zr', 'ligero_a', 'alta'),
('MG ROVER', 'Mg Zt', 'ligero_a', 'alta'),
('MG ROVER', 'R75', 'ligero_a', 'alta'),
('Mini', 'MINI Countryman E', 'ligero_a', 'alta'),
('Mini', 'MINI Aceman', 'ligero_a', 'alta'),
('Mini', 'MINI E', 'ligero_a', 'alta'),
('Mini', 'Cooper Conv', 'ligero_a', 'alta'),
('Mini', 'MINI 3 PTAS', 'ligero_a', 'alta'),
('Mini', 'MINI 5 PTAS', 'ligero_a', 'alta'),
('Mini', 'MINI CLUBMAN', 'ligero_a', 'alta'),
('Mini', 'MINI CONVERTIBLE', 'ligero_a', 'alta'),
('Mini', 'MINI COUPE', 'ligero_a', 'alta'),
('Mini', 'MINI E', 'ligero_a', 'alta'),
('Mini', 'MINI PACEMAN', 'ligero_a', 'alta'),
('Mini', 'MINI ROADSTER', 'ligero_a', 'alta'),
('Mini', 'Cooper S Jcw', 'ligero_a', 'alta'),
('Mini', 'Countryman S', 'ligero_a', 'alta'),
('Mini', 'Cooper S', 'ligero_a', 'alta'),
('Mini', 'Cooper S Clubman', 'ligero_a', 'alta'),
('Mini', 'Cooper S Conv', 'ligero_a', 'alta'),
('Mitsubishi', 'Lancer Evolution', 'ligero_a', 'alta'),
('Mitsubishi', 'Eclipse', 'ligero_a', 'alta'),
('Mitsubishi', 'Eclipse Conv', 'ligero_a', 'alta'),
('Nissan', 'Altima', 'ligero_a', 'alta'),
('Nissan', 'Altima Coupe', 'ligero_a', 'alta'),
('Nissan', 'Infinity I35', 'ligero_a', 'alta'),
('Nissan', 'Infinity Q45-M45', 'ligero_a', 'alta'),
('Nissan', 'Maxima', 'ligero_a', 'alta'),
('Nissan', '350 Z', 'ligero_a', 'alta'),
('Nissan', '370 Z', 'ligero_a', 'alta'),
('Nissan', 'Z', 'ligero_a', 'alta'),
('Nissan', 'Almera Dep', 'ligero_a', 'alta'),
('Peugeot', 'Rcz', 'ligero_a', 'alta'),
('Peugeot', '406 Coupe', 'ligero_a', 'alta'),
('Peugeot', '406 St Aut', 'ligero_a', 'alta'),
('Peugeot', '406 Sv V6', 'ligero_a', 'alta'),
('Peugeot', '407', 'ligero_a', 'alta'),
('Peugeot', '508', 'ligero_a', 'alta'),
('Peugeot', '607 Pack', 'ligero_a', 'alta'),
('Renault', 'Safrane', 'ligero_a', 'alta'),
('Renault', 'Laguna', 'ligero_a', 'alta'),
('Renault', 'Sandero R.S. 2.0', 'ligero_a', 'alta'),
('Renault', 'Sandero', 'ligero_a', 'alta'),
('Renault', 'Clio RS', 'ligero_a', 'alta'),
('Renault', 'Clio Renault Sport', 'ligero_a', 'alta'),
('SEAT', 'Leon', 'ligero_a', 'alta'),
('SEAT', 'Leon Cupra', 'ligero_a', 'alta'),
('SEAT', 'Leon Sc 2p', 'ligero_a', 'alta'),
('Smart', 'FORTWO', 'ligero_a', 'alta'),
('Smart', 'FORTWO', 'ligero_a', 'alta'),
('Smart', 'Forfour', 'ligero_a', 'alta'),
('Subaru', 'Legacy', 'ligero_a', 'alta'),
('Subaru', 'Legacy 2.0', 'ligero_a', 'alta'),
('Subaru', 'Legacy 2.5i', 'ligero_a', 'alta'),
('Subaru', 'Legacy 3.0', 'ligero_a', 'alta'),
('Subaru', 'Legacy 3.6', 'ligero_a', 'alta'),
('Subaru', 'Subaru BRZ', 'ligero_a', 'alta'),
('Subaru', 'WRX', 'ligero_a', 'alta'),
('Subaru', 'WRX STI', 'ligero_a', 'alta'),
('Suzuki', 'Kizashi', 'ligero_a', 'alta'),
('Toyota', 'Camry', 'ligero_a', 'alta'),
('Toyota', 'Prius', 'ligero_a', 'alta'),
('Toyota', 'Solara', 'ligero_a', 'alta'),
('Toyota', 'GR Corolla', 'ligero_a', 'alta'),
('Toyota', 'GR Yaris', 'ligero_a', 'alta'),
('Toyota', 'Mr2', 'ligero_a', 'alta'),
('Volkswagen', 'EOS', 'ligero_a', 'alta'),
('Volkswagen', 'Passat', 'ligero_a', 'alta'),
('Volkswagen', 'Passat Cc', 'ligero_a', 'alta'),
('Volkswagen', 'GTI', 'ligero_a', 'alta'),
('Volkswagen', 'Golf Gti', 'ligero_a', 'alta'),
('Volvo', 'C70 T5', 'ligero_a', 'alta'),
('Volvo', 'C30 2.4i', 'ligero_a', 'alta'),
('Volvo', 'C30 T5', 'ligero_a', 'alta'),
('Volvo', 'C40', 'ligero_a', 'alta'),
('Volvo', 'S60', 'ligero_a', 'alta'),
('Volvo', 'S60 R', 'ligero_a', 'alta'),
('Volvo', 'S60 T6', 'ligero_a', 'alta'),
('Volvo', 'V40', 'ligero_a', 'alta'),
('Volvo', 'V40 II', 'ligero_a', 'alta'),
('Volvo', 'V40 T4', 'ligero_a', 'alta'),
('Volvo', 'V40 T5', 'ligero_a', 'alta'),
('Volvo', 'V40cc', 'ligero_a', 'alta'),
('Volvo', 'V40cc T5 Awd', 'ligero_a', 'alta'),
('Volvo', 'V40cc T5 Fwd', 'ligero_a', 'alta'),
('Volvo', 'V60', 'ligero_a', 'alta'),
('Volvo', 'XC40', 'ligero_a', 'alta'),
('Volvo', 'S60 III', 'ligero_a', 'alta'),
('Volvo', 'C70 Cabrio', 'ligero_a', 'alta'),
('Volvo', 'S40 2.0t', 'ligero_a', 'alta'),
('Volvo', 'S40 T5', 'ligero_a', 'alta'),
('Volvo', 'S60 2.5t', 'ligero_a', 'alta'),
('Volvo', 'S60 CC', 'ligero_a', 'alta'),
('Volvo', 'S60 II', 'ligero_a', 'alta'),
('Volvo', 'S80 2.5t', 'ligero_a', 'alta'),
('Volvo', 'S80 3.2', 'ligero_a', 'alta'),
('Volvo', 'S80 T6', 'ligero_a', 'alta'),
('Volvo', 'S80 V8', 'ligero_a', 'alta'),
('Volvo', 'S90', 'ligero_a', 'alta'),
('Volvo', 'V50 T5', 'ligero_a', 'alta'),
('Volvo', 'V60 CC', 'ligero_a', 'alta'),
('Volvo', 'S 60 1.6', 'ligero_a', 'alta'),
('Zeekr', '001', 'ligero_a', 'alta'),
('Zeekr', '7X', 'ligero_a', 'alta'),
('Zeekr', 'X', 'ligero_a', 'alta'),
('Auteco', 'D2S 150', 'ligero_a', 'entrada'),
('Auteco', 'D2S 250', 'ligero_a', 'entrada'),
('Changan', 'ALSVIN', 'ligero_a', 'entrada'),
('Chrysler', 'Vision', 'ligero_a', 'entrada'),
('Chrysler', 'Atos', 'ligero_a', 'entrada'),
('Chrysler', 'I10', 'ligero_a', 'entrada'),
('Chrysler', 'Verna 3 Ptas', 'ligero_a', 'entrada'),
('Chrysler', 'Verna 4 Ptas', 'ligero_a', 'entrada'),
('Chrysler', 'Attitude', 'ligero_a', 'entrada'),
('Fiat', 'Fiat 500-', 'ligero_a', 'entrada'),
('Fiat', 'Albea Sedan', 'ligero_a', 'entrada'),
('Fiat', 'Argo', 'ligero_a', 'entrada'),
('Fiat', 'Mobi', 'ligero_a', 'entrada'),
('Fiat', 'Palio 1.8r', 'ligero_a', 'entrada'),
('Fiat', 'Palio Adventure', 'ligero_a', 'entrada'),
('Fiat', 'Palio Hatchback', 'ligero_a', 'entrada'),
('Fiat', 'Palio Sedan', 'ligero_a', 'entrada'),
('Fiat', 'Uno', 'ligero_a', 'entrada'),
('Fiat', 'Bravo', 'ligero_a', 'entrada'),
('Fiat', 'Fiat 500', 'ligero_a', 'entrada'),
('Fiat', 'Panda 4x2d', 'ligero_a', 'entrada'),
('Fiat', 'Panda 4x2m', 'ligero_a', 'entrada'),
('Fiat', 'Panda 4x4', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta Ikon', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta NA 5 DR', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta NA Sedan', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta Sedan / Ikon Notch', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta St', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta', 'ligero_a', 'entrada'),
('Ford Motor', 'Fiesta Sedan / Ikon Notch', 'ligero_a', 'entrada'),
('Ford Motor', 'Ka', 'ligero_a', 'entrada'),
('Ford Motor', 'Figo 5 DR', 'ligero_a', 'entrada'),
('Ford Motor', 'Figo Sedan', 'ligero_a', 'entrada'),
('Ford Motor', 'Ikon Hatch', 'ligero_a', 'entrada'),
('Geely', 'Emgrand', 'ligero_a', 'entrada'),
('General Motors', 'Aveo-', 'ligero_a', 'entrada'),
('General Motors', 'Chevy 3 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Chevy 4 PTAS', 'ligero_a', 'entrada'),
('General Motors', 'Chevy 5 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'G3 4 PTAS-', 'ligero_a', 'entrada'),
('General Motors', 'G3 5 PTAS-', 'ligero_a', 'entrada'),
('General Motors', 'Sonic 5 PTS-', 'ligero_a', 'entrada'),
('General Motors', 'Sonic-', 'ligero_a', 'entrada'),
('General Motors', 'Corsa 5 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Corsa Sedan 4 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Aveo', 'ligero_a', 'entrada'),
('General Motors', 'Aveo HB', 'ligero_a', 'entrada'),
('General Motors', 'G3 4 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Matiz 5 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Sonic', 'ligero_a', 'entrada'),
('General Motors', 'Spark EV 5 Ptas.', 'ligero_a', 'entrada'),
('General Motors', 'Spark NG', 'ligero_a', 'entrada'),
('General Motors', 'Bolt', 'ligero_a', 'entrada'),
('General Motors', 'Sonic 5 PTS', 'ligero_a', 'entrada'),
('General Motors', 'Volt 4 Ptas.', 'ligero_a', 'entrada'),
('General Motors', 'Beat', 'ligero_a', 'entrada'),
('General Motors', 'Beat 4 PTAS.', 'ligero_a', 'entrada'),
('General Motors', 'Spark', 'ligero_a', 'entrada'),
('General Motors', 'Palio 4 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Palio 5 Ptas', 'ligero_a', 'entrada'),
('General Motors', 'Palio Adventurer', 'ligero_a', 'entrada'),
('Great Wall Motor', 'ORA 03', 'ligero_a', 'entrada'),
('Honda', 'Fit-', 'ligero_a', 'entrada'),
('Honda', 'Fit', 'ligero_a', 'entrada'),
('Hyundai', 'Accent Hatchback', 'ligero_a', 'entrada'),
('Hyundai', 'Accent Sedan', 'ligero_a', 'entrada'),
('Hyundai', 'Grand I10', 'ligero_a', 'entrada'),
('Hyundai', 'Grand I10 Sedán', 'ligero_a', 'entrada'),
('JAC', 'E 30x', 'ligero_a', 'entrada'),
('JAC', 'E J4', 'ligero_a', 'entrada'),
('JAC', 'J4', 'ligero_a', 'entrada'),
('KIA', 'KIA K3 Hatchback', 'ligero_a', 'entrada'),
('KIA', 'KIA K3 Sedán', 'ligero_a', 'entrada'),
('KIA', 'KIA Río Sedan-', 'ligero_a', 'entrada'),
('KIA', 'Kia Río Hatchback-', 'ligero_a', 'entrada'),
('KIA', 'KIA Río Hatchback', 'ligero_a', 'entrada'),
('KIA', 'KIA Río Sedan', 'ligero_a', 'entrada'),
('Mazda', 'Mazda 2 Hatchback', 'ligero_a', 'entrada'),
('Mazda', 'Mazda 2 Sedán', 'ligero_a', 'entrada'),
('Mazda', 'Mazda 2-', 'ligero_a', 'entrada'),
('Mazda', 'Mazda 2', 'ligero_a', 'entrada'),
('MG Motor', 'MG3', 'ligero_a', 'entrada'),
('MG Motor', 'MG3HEV', 'ligero_a', 'entrada'),
('MG Motor', 'MG4', 'ligero_a', 'entrada'),
('Mini', 'Cooper', 'ligero_a', 'entrada'),
('Mitsubishi', 'Space Star', 'ligero_a', 'entrada'),
('Mitsubishi', 'Mirage', 'ligero_a', 'entrada'),
('Mitsubishi', 'Mirage G4', 'ligero_a', 'entrada'),
('MOTORNATION', 'BAIC D20', 'ligero_a', 'entrada'),
('MOTORNATION', 'BAIC X25', 'ligero_a', 'entrada'),
('MOTORNATION', 'CHANGAN ALSVIN', 'ligero_a', 'entrada'),
('MOTORNATION', 'JMC EV-BLACK', 'ligero_a', 'entrada'),
('Nissan', 'March', 'ligero_a', 'entrada'),
('Nissan', 'Platina 4 PTS', 'ligero_a', 'entrada'),
('Nissan', 'Tsuru 4 PTS', 'ligero_a', 'entrada'),
('Nissan', 'Aprio', 'ligero_a', 'entrada'),
('Nissan', 'Micra', 'ligero_a', 'entrada'),
('Omoda', 'O5', 'ligero_a', 'entrada'),
('Peugeot', '301', 'ligero_a', 'entrada');

insert into public.catalogo_vehiculos_tarifa (marca, modelo, categoria_tarifa, gama) values
('Peugeot', '206 3p', 'ligero_a', 'entrada'),
('Peugeot', '206 5p', 'ligero_a', 'entrada'),
('Peugeot', '206 Cc', 'ligero_a', 'entrada'),
('Peugeot', '206 Sw', 'ligero_a', 'entrada'),
('Peugeot', '207 3p', 'ligero_a', 'entrada'),
('Peugeot', '207 Compact', 'ligero_a', 'entrada'),
('Peugeot', '207 Compact 3p', 'ligero_a', 'entrada'),
('Peugeot', '207 Compact 5p', 'ligero_a', 'entrada'),
('Peugeot', '207 Sedan', 'ligero_a', 'entrada'),
('Peugeot', '208', 'ligero_a', 'entrada'),
('Peugeot', 'Nuevo 207', 'ligero_a', 'entrada'),
('Renault', 'Clio', 'ligero_a', 'entrada'),
('Renault', 'Kwid', 'ligero_a', 'entrada'),
('Renault', 'Logan', 'ligero_a', 'entrada'),
('Renault', 'Kwid e-Tech', 'ligero_a', 'entrada'),
('Renault', 'Scala', 'ligero_a', 'entrada'),
('Renault', 'Twizy', 'ligero_a', 'entrada'),
('Renault', 'Euro Clio', 'ligero_a', 'entrada'),
('Renault', 'MEGANE E-TECH', 'ligero_a', 'entrada'),
('Renault', 'ZOE', 'ligero_a', 'entrada'),
('SEAT', 'Exeo', 'ligero_a', 'entrada'),
('SEAT', 'Altea', 'ligero_a', 'entrada'),
('SEAT', 'Cordoba', 'ligero_a', 'entrada'),
('SEAT', 'Freetrack', 'ligero_a', 'entrada'),
('SEAT', 'Ibiza', 'ligero_a', 'entrada'),
('SEAT', 'Ibiza 2 Ptas', 'ligero_a', 'entrada'),
('SEAT', 'Ibiza 4 Ptas', 'ligero_a', 'entrada'),
('Smart', 'Roadster', 'ligero_a', 'entrada'),
('Smart', 'Otros Smart', 'ligero_a', 'entrada'),
('Suzuki', 'Baleno', 'ligero_a', 'entrada'),
('Suzuki', 'DZIRE', 'ligero_a', 'entrada'),
('Suzuki', 'Ignis', 'ligero_a', 'entrada'),
('Suzuki', 'SWIFT BG', 'ligero_a', 'entrada'),
('Suzuki', 'Swift', 'ligero_a', 'entrada'),
('Toyota', 'Yaris-R', 'ligero_a', 'entrada'),
('Toyota', 'Yaris Hatchback', 'ligero_a', 'entrada'),
('Toyota', 'Prius-C', 'ligero_a', 'entrada'),
('Toyota', 'Yaris Hatchback', 'ligero_a', 'entrada'),
('Toyota', 'Yaris Sedan', 'ligero_a', 'entrada'),
('Toyota', 'Yaris Hatchback', 'ligero_a', 'entrada'),
('Toyota', 'Yaris Sedan', 'ligero_a', 'entrada'),
('Volkswagen', 'Sedan', 'ligero_a', 'entrada'),
('Volkswagen', 'Derby', 'ligero_a', 'entrada'),
('Volkswagen', 'Crossfox', 'ligero_a', 'entrada'),
('Volkswagen', 'Gol', 'ligero_a', 'entrada'),
('Volkswagen', 'Gol Sedan', 'ligero_a', 'entrada'),
('Volkswagen', 'Lupo 2 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'Lupo 4 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'Pointer 2 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'Pointer 4 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'Polo 4 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'Polo 5 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'UP!', 'ligero_a', 'entrada'),
('Volkswagen', 'Virtus', 'ligero_a', 'entrada'),
('Volkswagen', 'Volkswagen Tera', 'ligero_a', 'entrada'),
('Volkswagen', 'Polo GTI', 'ligero_a', 'entrada'),
('Volkswagen', 'Polo 4 Ptas', 'ligero_a', 'entrada'),
('Volkswagen', 'Vento', 'ligero_a', 'entrada'),
('Volkswagen', 'Virtus', 'ligero_a', 'entrada'),
('Auteco', 'E-VAN S1.0T PRO', 'ligero_b', 'entrada'),
('Auteco', 'E-Van B2.4T', 'ligero_b', 'entrada'),
('Changan', 'HONOR S', 'ligero_b', 'entrada'),
('Chrysler', 'Chrysler Pacifica', 'ligero_b', 'entrada'),
('Chrysler', 'Grand Caravan', 'ligero_b', 'entrada'),
('Chrysler', 'Voyager Town&Country LTD', 'ligero_b', 'entrada'),
('Chrysler', 'Voyager Town&Country LX', 'ligero_b', 'entrada'),
('Chrysler', 'Voyager', 'ligero_b', 'entrada'),
('Ford Motor', 'Freestar', 'ligero_b', 'entrada'),
('Ford Motor', 'Club Wagon', 'ligero_b', 'entrada'),
('Ford Motor', 'Econoline', 'ligero_b', 'entrada'),
('Ford Motor', 'Expedition', 'ligero_b', 'entrada'),
('General Motors', 'Escalade ESV SUV AWD', 'ligero_b', 'entrada'),
('General Motors', 'Escalade EXT UUV 4X4', 'ligero_b', 'entrada'),
('General Motors', 'Brightdrop', 'ligero_b', 'entrada'),
('General Motors', 'Chevrolet Express MAX Cargo Van', 'ligero_b', 'entrada'),
('General Motors', 'Tornado Van', 'ligero_b', 'entrada'),
('General Motors', 'Chevrolet Express Cargo Van', 'ligero_b', 'entrada'),
('General Motors', 'Chevrolet Express Cutaway', 'ligero_b', 'entrada'),
('General Motors', 'Chevrolet Express Passenger Van', 'ligero_b', 'entrada'),
('General Motors', 'Escalade ESV SUV AWD', 'ligero_b', 'entrada'),
('General Motors', 'Escalade Suv', 'ligero_b', 'entrada'),
('General Motors', 'H2 Sut', 'ligero_b', 'entrada'),
('General Motors', 'H2 Suv', 'ligero_b', 'entrada'),
('General Motors', 'Montana Sv6 Van', 'ligero_b', 'entrada'),
('General Motors', 'Uplander Van', 'ligero_b', 'entrada'),
('General Motors', 'Venture Van', 'ligero_b', 'entrada'),
('Honda', 'Odyssey', 'ligero_b', 'entrada'),
('Honda', 'Odyssey', 'ligero_b', 'entrada'),
('Hyundai', 'Starex', 'ligero_b', 'entrada'),
('JAC', 'E SUNRAY', 'ligero_b', 'entrada'),
('JAC', 'E Sunray City', 'ligero_b', 'entrada'),
('JAC', 'SUNRAY', 'ligero_b', 'entrada'),
('JAC', 'Sunray City', 'ligero_b', 'entrada'),
('KIA', 'Sedona', 'ligero_b', 'entrada'),
('Lincoln', 'Aviator', 'ligero_b', 'entrada'),
('Lincoln', 'Mariner', 'ligero_b', 'entrada'),
('Lincoln', 'Navigator', 'ligero_b', 'entrada'),
('Mitsubishi', 'Grandis', 'ligero_b', 'entrada'),
('MOTORNATION', 'BAIC M50S', 'ligero_b', 'entrada'),
('MOTORNATION', 'DFSK EC35', 'ligero_b', 'entrada'),
('Nissan', 'NV2500 V8 Toldo Alto', 'ligero_b', 'entrada'),
('Nissan', 'NV2500 V6 Toldo Alto', 'ligero_b', 'entrada'),
('Nissan', 'NV2500 V6 Toldo Bajo', 'ligero_b', 'entrada'),
('Nissan', 'NV2500 V8 Toldo Bajo', 'ligero_b', 'entrada'),
('Nissan', 'Quest', 'ligero_b', 'entrada'),
('Peugeot', 'Partner Rapid', 'ligero_b', 'entrada'),
('Peugeot', 'E-Partner', 'ligero_b', 'entrada'),
('Renault', 'Master', 'ligero_b', 'entrada'),
('Renault', 'Master E- Tech eléctrico', 'ligero_b', 'entrada'),
('SEAT', 'Alhambra', 'ligero_b', 'entrada'),
('Toyota', 'Sienna', 'ligero_b', 'entrada'),
('Volkswagen', 'Routan', 'ligero_b', 'entrada'),
('Volkswagen', 'Sharan', 'ligero_b', 'entrada'),
('Porsche', 'Cayenne', 'ligero_b', 'media'),
('Porsche', 'Macan', 'ligero_b', 'media'),
('Changan', 'Eado Plus', 'ligero_a', 'media'),
('Changan', 'Eado Plus IDD', 'ligero_a', 'media'),
('Chrysler', 'PT Cruiser', 'ligero_a', 'media'),
('Chrysler', 'Pt Cruiser Conv', 'ligero_a', 'media'),
('Chrysler', 'Nuevo Attitude', 'ligero_a', 'media'),
('Chrysler', 'Avenger', 'ligero_a', 'media'),
('Chrysler', 'Caliber', 'ligero_a', 'media'),
('Chrysler', 'Cirrus', 'ligero_a', 'media'),
('Chrysler', 'Cirrus Coupe', 'ligero_a', 'media'),
('Chrysler', 'Dart', 'ligero_a', 'media'),
('Chrysler', 'Neon', 'ligero_a', 'media'),
('Chrysler', 'Stratus', 'ligero_a', 'media'),
('Chrysler', 'Dodge Neon', 'ligero_a', 'media'),
('Fiat', 'Nuevo Palio', 'ligero_a', 'media'),
('Fiat', 'Grande Punto 3 Ptas', 'ligero_a', 'media'),
('Fiat', 'Grande Punto 5 Ptas', 'ligero_a', 'media'),
('Fiat', 'Grande Punto Turbo', 'ligero_a', 'media'),
('Fiat', '500L', 'ligero_a', 'media'),
('Fiat', 'Linea', 'ligero_a', 'media'),
('Ford Motor', 'Focus ZX3', 'ligero_a', 'media'),
('Ford Motor', 'Fusion', 'ligero_a', 'media'),
('Ford Motor', 'Fusion Hibrido', 'ligero_a', 'media'),
('Ford Motor', 'Focus St', 'ligero_a', 'media'),
('Ford Motor', 'Mondeo', 'ligero_a', 'media'),
('Ford Motor', 'Focus Sedan', 'ligero_a', 'media'),
('Ford Motor', 'Focus 5 Dr', 'ligero_a', 'media'),
('General Motors', 'Cruze 4 PTAS-', 'ligero_a', 'media'),
('General Motors', 'Cruze 5 Ptas', 'ligero_a', 'media'),
('General Motors', 'HHR 5 PTAS', 'ligero_a', 'media'),
('General Motors', 'Onix', 'ligero_a', 'media'),
('General Motors', 'Sunfire 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Sunfire GT 2 Ptas', 'ligero_a', 'media'),
('General Motors', 'Vectra 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Zafira Monocab', 'ligero_a', 'media'),
('General Motors', 'Astra 3 Ptas', 'ligero_a', 'media'),
('General Motors', 'Astra 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Astra 5 Ptas', 'ligero_a', 'media'),
('General Motors', 'Meriva Monocab', 'ligero_a', 'media'),
('General Motors', 'Cavalier 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Onix', 'ligero_a', 'media'),
('General Motors', 'Cruze 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Epica', 'ligero_a', 'media'),
('General Motors', 'Optra', 'ligero_a', 'media'),
('General Motors', 'G5 2 Ptas', 'ligero_a', 'media'),
('General Motors', 'G5 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'G6 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Grand Am 4 Ptas', 'ligero_a', 'media'),
('General Motors', 'Malibu 4 Ptas', 'ligero_a', 'media'),
('Honda', 'Honda City', 'ligero_a', 'media'),
('Honda', 'Civic', 'ligero_a', 'media'),
('Honda', 'Civic 2pts Ta', 'ligero_a', 'media'),
('Honda', 'Civic Si', 'ligero_a', 'media'),
('Honda', 'Honda City', 'ligero_a', 'media'),
('Honda', 'Civic', 'ligero_a', 'media'),
('Honda', 'Civic 2pts Ta', 'ligero_a', 'media'),
('Honda', 'Civic 2pts Tm', 'ligero_a', 'media'),
('Honda', 'Civic Ima', 'ligero_a', 'media'),
('Honda', 'Insight Hybrid', 'ligero_a', 'media'),
('Honda', 'Honda City', 'ligero_a', 'media'),
('Honda', 'CR-Z', 'ligero_a', 'media'),
('Honda', 'Honda City', 'ligero_a', 'media'),
('Hyundai', 'HB20 HATCHBACK', 'ligero_a', 'media'),
('Hyundai', 'HB20 SEDAN', 'ligero_a', 'media'),
('Hyundai', 'Ioniq', 'ligero_a', 'media'),
('Hyundai', 'Ioniq 5', 'ligero_a', 'media'),
('Hyundai', 'Elantra', 'ligero_a', 'media'),
('Hyundai', 'Sonata', 'ligero_a', 'media'),
('JAC', 'E 10X', 'ligero_a', 'media'),
('JAC', 'E J7', 'ligero_a', 'media'),
('JAC', 'J7', 'ligero_a', 'media'),
('JAC', 'Traveler', 'ligero_a', 'media'),
('KIA', 'Forte Hatchback', 'ligero_a', 'media'),
('KIA', 'Forte-', 'ligero_a', 'media'),
('KIA', 'K4 Hatchback', 'ligero_a', 'media'),
('KIA', 'K4 Sedán', 'ligero_a', 'media'),
('KIA', 'Forte', 'ligero_a', 'media'),
('KIA', 'Forte Hatchback', 'ligero_a', 'media'),
('Mazda', 'Mazda 3 Hatchback', 'ligero_a', 'media'),
('Mazda', 'Mazda 3 Sedán-', 'ligero_a', 'media'),
('Mazda', 'Mazda 3 Hatchback', 'ligero_a', 'media'),
('Mazda', 'Mazda 3 Sedán', 'ligero_a', 'media'),
('Mazda', 'Mazda 5', 'ligero_a', 'media'),
('Mercedes Benz', 'B 200', 'ligero_a', 'media'),
('Mercedes Benz', 'A 160', 'ligero_a', 'media'),
('MG Motor', 'GT', 'ligero_a', 'media'),
('MG Motor', 'MG5', 'ligero_a', 'media'),
('Mitsubishi', 'Galant', 'ligero_a', 'media'),
('Mitsubishi', 'Lancer', 'ligero_a', 'media'),
('MOTORNATION', 'BAIC EU5', 'ligero_a', 'media'),
('MOTORNATION', 'BAIC U5', 'ligero_a', 'media'),
('Nissan', 'Note', 'ligero_a', 'media'),
('Nissan', 'Sentra', 'ligero_a', 'media'),
('Nissan', 'Sentra 4 PTS', 'ligero_a', 'media'),
('Nissan', 'Sentra SE R', 'ligero_a', 'media'),
('Nissan', 'Tiida 5 PTS', 'ligero_a', 'media'),
('Nissan', 'Tiida Sedan', 'ligero_a', 'media'),
('Nissan', 'Versa', 'ligero_a', 'media'),
('Nissan', 'Juke', 'ligero_a', 'media'),
('Nissan', 'Leaf', 'ligero_a', 'media'),
('Nissan', 'Almera 4 Pts', 'ligero_a', 'media'),
('Peugeot', '307 4p', 'ligero_a', 'media'),
('Peugeot', 'Grand Raid', 'ligero_a', 'media'),
('Peugeot', '207 CC', 'ligero_a', 'media'),
('Peugeot', '207 Rc', 'ligero_a', 'media'),
('Peugeot', '307 3p', 'ligero_a', 'media'),
('Peugeot', '307 5p', 'ligero_a', 'media'),
('Peugeot', '307 Break', 'ligero_a', 'media'),
('Peugeot', '307 Cc', 'ligero_a', 'media'),
('Peugeot', '307 Sw', 'ligero_a', 'media'),
('Peugeot', '308', 'ligero_a', 'media'),
('Peugeot', '308 Cc', 'ligero_a', 'media'),
('Peugeot', 'Grand Raid Hdi', 'ligero_a', 'media'),
('Renault', 'Scenic', 'ligero_a', 'media'),
('Renault', 'Kangoo 7 Plazas', 'ligero_a', 'media'),
('Renault', 'Kangoo Vp', 'ligero_a', 'media'),
('Renault', 'Kardian', 'ligero_a', 'media'),
('Renault', 'Stepway', 'ligero_a', 'media'),
('Renault', 'Fluence', 'ligero_a', 'media'),
('Renault', 'Megane II 3 Ptas', 'ligero_a', 'media'),
('Renault', 'Megane II 3 Ptas Sport', 'ligero_a', 'media'),
('Renault', 'Megane II 5 Ptas', 'ligero_a', 'media'),
('Renault', 'Megane Ii Cc', 'ligero_a', 'media'),
('Renault', 'Megane II Gt 3 Ptas', 'ligero_a', 'media'),
('Renault', 'Megane II Gt 5 Ptas', 'ligero_a', 'media'),
('Renault', 'Scenic II', 'ligero_a', 'media'),
('Renault', 'Megane II Sedan', 'ligero_a', 'media'),
('SEAT', 'Nuevo Toledo', 'ligero_a', 'media'),
('SEAT', 'Leon ST', 'ligero_a', 'media'),
('SEAT', 'Leon Sc 2p', 'ligero_a', 'media'),
('SEAT', 'Toledo', 'ligero_a', 'media'),
('Subaru', 'Impreza', 'ligero_a', 'media'),
('Subaru', 'Impreza HB', 'ligero_a', 'media'),
('Suzuki', 'Ciaz', 'ligero_a', 'media'),
('Suzuki', 'Ertiga', 'ligero_a', 'media'),
('Suzuki', 'Aerio Ta', 'ligero_a', 'media'),
('Suzuki', 'Aerio Tm', 'ligero_a', 'media'),
('Suzuki', 'Sx4 Sedan Ta', 'ligero_a', 'media'),
('Suzuki', 'Sx4 Sedan Tm', 'ligero_a', 'media'),
('Suzuki', 'Sx4 X-Over Ta', 'ligero_a', 'media'),
('Suzuki', 'Sx4 X-Over Tm', 'ligero_a', 'media'),
('Toyota', 'Corolla', 'ligero_a', 'media'),
('Toyota', 'Matrix', 'ligero_a', 'media'),
('Toyota', 'Corolla', 'ligero_a', 'media'),
('Toyota', 'Avanza', 'ligero_a', 'media'),
('Volkswagen', 'Beetle', 'ligero_a', 'media'),
('Volkswagen', 'Beetle Cabrio', 'ligero_a', 'media'),
('Volkswagen', 'Bora', 'ligero_a', 'media'),
('Volkswagen', 'Bora TDI', 'ligero_a', 'media'),
('Volkswagen', 'Golf Variant-/Crossgolf', 'ligero_a', 'media'),
('Volkswagen', 'Golf-', 'ligero_a', 'media'),
('Volkswagen', 'Jetta', 'ligero_a', 'media'),
('Volkswagen', 'Jetta 4 PTAS', 'ligero_a', 'media'),
('Volkswagen', 'Jetta TDI', 'ligero_a', 'media'),
('Volkswagen', 'Nuevo Jetta', 'ligero_a', 'media'),
('Volkswagen', 'Nuevo Jetta TDI', 'ligero_a', 'media'),
('Volkswagen', 'Sportwagen', 'ligero_a', 'media'),
('Volkswagen', 'Sport Van', 'ligero_a', 'media'),
('Volkswagen', 'Golf', 'ligero_a', 'media'),
('Volkswagen', 'Pointer Wagon', 'ligero_a', 'media'),
('Acura', 'ADX', 'ligero_b', 'media'),
('Acura', 'Mdx', 'ligero_b', 'media'),
('Acura', 'ZDX', 'ligero_b', 'media'),
('Acura', 'Mdx', 'ligero_b', 'media'),
('Acura', 'Rdx', 'ligero_b', 'media'),
('Alfa Romeo', 'TONALE', 'ligero_b', 'media'),
('Alfa Romeo', 'Junior', 'ligero_b', 'media'),
('Audi', 'Q5', 'ligero_b', 'media'),
('Audi', 'Audi Q7 3.0 TDI', 'ligero_b', 'media'),
('Audi', 'Audi Q7 4.2', 'ligero_b', 'media'),
('Audi', 'Q5 2.0T', 'ligero_b', 'media'),
('Audi', 'Q5 3.0 TDI', 'ligero_b', 'media'),
('Audi', 'Q5 3.2', 'ligero_b', 'media'),
('Audi', 'Q7', 'ligero_b', 'media'),
('Audi', 'Q7 3.0T FSI', 'ligero_b', 'media'),
('Audi', 'Q8', 'ligero_b', 'media'),
('Audi', 'e-tron', 'ligero_b', 'media'),
('Audi', 'Audi Q7 3.6', 'ligero_b', 'media'),
('Audi', 'Audi Q7 4.2 TDI', 'ligero_b', 'media'),
('Audi', 'Q7-', 'ligero_b', 'media'),
('Audi', 'Q3-', 'ligero_b', 'media'),
('Audi', 'Q 3', 'ligero_b', 'media'),
('Audi', 'Q3 SB', 'ligero_b', 'media'),
('Auteco', 'E-TRUCK B2.0T', 'ligero_b', 'media'),
('Auteco', 'RICH 6 EV', 'ligero_b', 'media'),
('Auteco', 'Rich 7EV 4x4', 'ligero_b', 'media'),
('BMW', 'X1', 'ligero_b', 'media'),
('BMW', 'X2', 'ligero_b', 'media'),
('BMW', 'X5 M', 'ligero_b', 'media'),
('BMW', 'X6 M', 'ligero_b', 'media'),
('BMW', 'iX', 'ligero_b', 'media'),
('BMW', 'iX2', 'ligero_b', 'media'),
('BMW', 'X3 2.5I', 'ligero_b', 'media'),
('BMW', 'X3 3.0I', 'ligero_b', 'media'),
('BMW', 'iX3', 'ligero_b', 'media'),
('BMW', 'X3', 'ligero_b', 'media'),
('BMW', 'X3 Xdrive 28ia', 'ligero_b', 'media'),
('BMW', 'X3 Xdrive35ia', 'ligero_b', 'media'),
('BMW', 'X4', 'ligero_b', 'media'),
('BMW', 'X5', 'ligero_b', 'media'),
('BMW', 'X5 3.0I', 'ligero_b', 'media'),
('BMW', 'X5 4.4I', 'ligero_b', 'media'),
('BMW', 'X5 4.8I', 'ligero_b', 'media'),
('BMW', 'X5 Xdrive35I', 'ligero_b', 'media'),
('BMW', 'X5 Xdrive50I', 'ligero_b', 'media'),
('BMW', 'X6', 'ligero_b', 'media'),
('BMW', 'X7', 'ligero_b', 'media'),
('Changan', 'CS35 PLUS', 'ligero_b', 'media'),
('Changan', 'CS55 PLUS', 'ligero_b', 'media'),
('Changan', 'CS55 Plus IDD', 'ligero_b', 'media'),
('Changan', 'CS75', 'ligero_b', 'media'),
('Changan', 'CS95', 'ligero_b', 'media'),
('Changan', 'DEEPAL S07 BEV', 'ligero_b', 'media'),
('Changan', 'DEEPAL S07 REEV', 'ligero_b', 'media'),
('Changan', 'UNI-K', 'ligero_b', 'media'),
('Changan', 'HUNTER CHASIS', 'ligero_b', 'media'),
('Changan', 'HUNTER PLUS', 'ligero_b', 'media'),
('Changan', 'HUNTER WORK', 'ligero_b', 'media'),
('Changan', 'NEW STAR TRUCK', 'ligero_b', 'media'),
('Chirey', 'Tiggo 2', 'ligero_b', 'media'),
('Chirey', 'Tiggo 4', 'ligero_b', 'media'),
('Chirey', 'Tiggo 7', 'ligero_b', 'media'),
('Chirey', 'Tiggo 7 Pro e+', 'ligero_b', 'media'),
('Chirey', 'Tiggo 8', 'ligero_b', 'media'),
('Chirey', 'Tiggo 8 Pro e+', 'ligero_b', 'media'),
('Chrysler', 'Jeep Compass-', 'ligero_b', 'media'),
('Chrysler', 'Journey', 'ligero_b', 'media'),
('Chrysler', 'Promaster', 'ligero_b', 'media'),
('Chrysler', 'Commander', 'ligero_b', 'media'),
('Chrysler', 'Renegade', 'ligero_b', 'media'),
('Chrysler', 'Pacifica', 'ligero_b', 'media'),
('Chrysler', 'Journey', 'ligero_b', 'media'),
('Chrysler', 'H100 Van', 'ligero_b', 'media'),
('Chrysler', 'H100 Wagon', 'ligero_b', 'media'),
('Chrysler', 'Aspen', 'ligero_b', 'media'),
('Chrysler', 'Cherokee', 'ligero_b', 'media'),
('Chrysler', 'Commander Xk', 'ligero_b', 'media'),
('Chrysler', 'Durango', 'ligero_b', 'media'),
('Chrysler', 'Grand Cherokee', 'ligero_b', 'media'),
('Chrysler', 'Jeep Compass', 'ligero_b', 'media'),
('Chrysler', 'Liberty', 'ligero_b', 'media'),
('Chrysler', 'Nitro', 'ligero_b', 'media'),
('Chrysler', 'Patriot', 'ligero_b', 'media'),
('Chrysler', 'Wagoneer', 'ligero_b', 'media'),
('Chrysler', 'Wrangler', 'ligero_b', 'media'),
('Chrysler', 'Crew Cab-', 'ligero_b', 'media'),
('Chrysler', 'RAM 1200', 'ligero_b', 'media'),
('Chrysler', 'RAM 1500-', 'ligero_b', 'media'),
('Chrysler', 'RAM 2500-', 'ligero_b', 'media'),
('Chrysler', 'RAM 4000', 'ligero_b', 'media'),
('Chrysler', 'RAM 4000 Diesel', 'ligero_b', 'media'),
('Chrysler', 'Promaster Rapid', 'ligero_b', 'media'),
('Chrysler', 'RAM 700', 'ligero_b', 'media'),
('Chrysler', 'H100', 'ligero_b', 'media'),
('Chrysler', 'Crew Cab', 'ligero_b', 'media'),
('Chrysler', 'Dakota', 'ligero_b', 'media'),
('Chrysler', 'JT', 'ligero_b', 'media'),
('Chrysler', 'Mega Cab', 'ligero_b', 'media'),
('Chrysler', 'Quad Cab', 'ligero_b', 'media'),
('Chrysler', 'RAM 4000', 'ligero_b', 'media'),
('Chrysler', 'RAM DS', 'ligero_b', 'media'),
('Chrysler', 'Ram 1500', 'ligero_b', 'media'),
('Chrysler', 'Ram 2500', 'ligero_b', 'media'),
('Chrysler', 'Dodge 1000', 'ligero_b', 'media'),
('Fiat', 'FASTBACK', 'ligero_b', 'media'),
('Fiat', 'Idea', 'ligero_b', 'media'),
('Fiat', 'Pulse', 'ligero_b', 'media'),
('Fiat', 'Strada Adventure', 'ligero_b', 'media'),
('Fiat', 'Ducato', 'ligero_b', 'media'),
('Ford Motor', 'Ranger', 'ligero_b', 'media'),
('Ford Motor', 'Ranger Crew Cab', 'ligero_b', 'media'),
('Ford Motor', 'Courier', 'ligero_b', 'media'),
('Ford Motor', 'E-Transit', 'ligero_b', 'media'),
('Ford Motor', 'F 250 Super Duty', 'ligero_b', 'media'),
('Ford Motor', 'F-350', 'ligero_b', 'media'),
('Ford Motor', 'F-450', 'ligero_b', 'media'),
('Ford Motor', 'F-550', 'ligero_b', 'media'),
('Ford Motor', 'F450 Diesel', 'ligero_b', 'media'),
('Ford Motor', 'F550 Diesel', 'ligero_b', 'media'),
('Ford Motor', 'Lobo Crew Cab', 'ligero_b', 'media'),
('Ford Motor', 'Lobo Regular Cab', 'ligero_b', 'media'),
('Ford Motor', 'New F150 / F-150', 'ligero_b', 'media'),
('Ford Motor', 'Ranger Chassis', 'ligero_b', 'media'),
('Ford Motor', 'Ranger Larga', 'ligero_b', 'media'),
('Ford Motor', 'Transit Courier', 'ligero_b', 'media'),
('Ford Motor', 'Bronco Sport', 'ligero_b', 'media'),
('Ford Motor', 'Mustang Mach-E', 'ligero_b', 'media'),
('Ford Motor', 'Ecosport', 'ligero_b', 'media'),
('Ford Motor', 'Edge', 'ligero_b', 'media'),
('Ford Motor', 'Territory', 'ligero_b', 'media'),
('Ford Motor', 'Bronco', 'ligero_b', 'media'),
('Ford Motor', 'Escape', 'ligero_b', 'media'),
('Ford Motor', 'Escape HEV', 'ligero_b', 'media'),
('Ford Motor', 'Excursion', 'ligero_b', 'media'),
('Ford Motor', 'Explorer', 'ligero_b', 'media'),
('Ford Motor', 'Explorer Sport Trac', 'ligero_b', 'media'),
('Ford Motor', 'Transit', 'ligero_b', 'media'),
('Ford Motor', 'Transit Pasajeros', 'ligero_b', 'media'),
('Ford Motor', 'F 150', 'ligero_b', 'media'),
('Ford Motor', 'F 250', 'ligero_b', 'media'),
('Ford Motor', 'F 350', 'ligero_b', 'media'),
('Ford Motor', 'F 450', 'ligero_b', 'media'),
('Ford Motor', 'F 450 Diesel', 'ligero_b', 'media'),
('Ford Motor', 'F 550', 'ligero_b', 'media'),
('Ford Motor', 'F 550 Diesel', 'ligero_b', 'media'),
('Ford Motor', 'H - 215', 'ligero_b', 'media'),
('Ford Motor', 'Maverick', 'ligero_b', 'media'),
('Foton', 'MILER', 'ligero_b', 'media'),
('Foton', 'S3', 'ligero_b', 'media'),
('Foton', 'S3 EV', 'ligero_b', 'media'),
('Foton', 'TM 3', 'ligero_b', 'media'),
('Foton', 'TM EV', 'ligero_b', 'media'),
('Foton', 'TUNLAND', 'ligero_b', 'media'),
('Foton', 'Tunland EV', 'ligero_b', 'media'),
('Foton', 'WONDER', 'ligero_b', 'media'),
('Foton', 'Wonder EV', 'ligero_b', 'media'),
('Foton', 'HI VAN EV', 'ligero_b', 'media'),
('Foton', 'HI-VAN', 'ligero_b', 'media'),
('Foton', 'VIEW', 'ligero_b', 'media'),
('Foton', 'VIEW EV', 'ligero_b', 'media'),
('Geely', 'Cityray', 'ligero_b', 'media'),
('Geely', 'Coolray', 'ligero_b', 'media'),
('Geely', 'EX2', 'ligero_b', 'media'),
('Geely', 'EX5', 'ligero_b', 'media'),
('Geely', 'EX5 EM-i', 'ligero_b', 'media'),
('Geely', 'Geometry C', 'ligero_b', 'media'),
('Geely', 'Gx3 Pro', 'ligero_b', 'media'),
('Geely', 'Monjaro', 'ligero_b', 'media'),
('Geely', 'Okavango', 'ligero_b', 'media'),
('Geely', 'Starray', 'ligero_b', 'media'),
('General Motors', 'Avalanche UUV', 'ligero_b', 'media'),
('General Motors', 'Cheyenne Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Cheyenne Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'GMC Sierra Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Kodiak Chassis Cab Class 6 PBV23,900', 'ligero_b', 'media'),
('General Motors', 'Kodiak Chassis Cab Class 7 PBV33,000', 'ligero_b', 'media'),
('General Motors', 'Kodiak Chassis Cab Class 8 PBV36,000', 'ligero_b', 'media'),
('General Motors', 'Sierra Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Sierra Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Silverado 1500 Cabina Regular-', 'ligero_b', 'media'),
('General Motors', 'Silverado 2500 Cabina Regular-', 'ligero_b', 'media'),
('General Motors', 'Silverado 2500 Doble Cabina-', 'ligero_b', 'media'),
('General Motors', 'Silverado 3500 Chassis Cab', 'ligero_b', 'media'),
('General Motors', 'Silverado 3500 HD Chassis Cab Heavy Duty', 'ligero_b', 'media'),
('General Motors', 'Silverado Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Silverado Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Montana Crew Cab', 'ligero_b', 'media'),
('General Motors', 'S10', 'ligero_b', 'media'),
('General Motors', 'Tornado Pickup', 'ligero_b', 'media'),
('General Motors', 'Luv Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Luv Chasis Cabina', 'ligero_b', 'media'),
('General Motors', 'Luv Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'S10 Max Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'S10 Max Chassis', 'ligero_b', 'media'),
('General Motors', 'S10 Max Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Canyon', 'ligero_b', 'media'),
('General Motors', 'Canyon Crew Cab 4x4', 'ligero_b', 'media'),
('General Motors', 'Cheyenne Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Colorado Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'GMC Sierra Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Hummer EV Pickup', 'ligero_b', 'media'),
('General Motors', 'P-30 Fwd Control Chassis', 'ligero_b', 'media'),
('General Motors', 'Sierra Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Silverado 1500 Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Silverado 2500 Cabina Extendida', 'ligero_b', 'media'),
('General Motors', 'Silverado 2500 Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Silverado 2500 Cheyenne Crew Cab 4x4', 'ligero_b', 'media'),
('General Motors', 'Silverado 2500 Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Colorado Cabina Regular', 'ligero_b', 'media'),
('General Motors', 'Colorado Doble Cabina', 'ligero_b', 'media'),
('General Motors', 'Aztek SUV', 'ligero_b', 'media'),
('General Motors', 'Blazer', 'ligero_b', 'media'),
('General Motors', 'Blazer EV', 'ligero_b', 'media'),
('General Motors', 'Captiva Sport', 'ligero_b', 'media'),
('General Motors', 'Equinox EV', 'ligero_b', 'media'),
('General Motors', 'Equinox SUV-', 'ligero_b', 'media'),
('General Motors', 'Escalade IQ Suv', 'ligero_b', 'media'),
('General Motors', 'Escalade IQL Suv', 'ligero_b', 'media'),
('General Motors', 'Optiq', 'ligero_b', 'media'),
('General Motors', 'SRX SUV-', 'ligero_b', 'media'),
('General Motors', 'Suburban SUV-', 'ligero_b', 'media'),
('General Motors', 'Terrain SUV-', 'ligero_b', 'media'),
('General Motors', 'Trax', 'ligero_b', 'media'),
('General Motors', 'Tracker', 'ligero_b', 'media'),
('General Motors', 'Terrain Suv', 'ligero_b', 'media'),
('General Motors', 'Tracker Suv', 'ligero_b', 'media');

insert into public.catalogo_vehiculos_tarifa (marca, modelo, categoria_tarifa, gama) values
('General Motors', 'Captiva SUV', 'ligero_b', 'media'),
('General Motors', 'Envision SUV', 'ligero_b', 'media'),
('General Motors', 'Groove SUV', 'ligero_b', 'media'),
('General Motors', 'Spark EUV 4 dr.', 'ligero_b', 'media'),
('General Motors', 'Encore', 'ligero_b', 'media'),
('General Motors', 'Envista SUV', 'ligero_b', 'media'),
('General Motors', 'Acadia', 'ligero_b', 'media'),
('General Motors', 'Bolt EUV', 'ligero_b', 'media'),
('General Motors', 'Enclave', 'ligero_b', 'media'),
('General Motors', 'Equinox Suv', 'ligero_b', 'media'),
('General Motors', 'H3 Suv', 'ligero_b', 'media'),
('General Motors', 'H3 T', 'ligero_b', 'media'),
('General Motors', 'Hummer EV SUV', 'ligero_b', 'media'),
('General Motors', 'Lyriq SUV', 'ligero_b', 'media'),
('General Motors', 'Pontiac Torrent Suv', 'ligero_b', 'media'),
('General Motors', 'Sonora Suv', 'ligero_b', 'media'),
('General Motors', 'Srx Suv', 'ligero_b', 'media'),
('General Motors', 'Suburban Suv', 'ligero_b', 'media'),
('General Motors', 'Tahoe', 'ligero_b', 'media'),
('General Motors', 'Trailblazer Suv', 'ligero_b', 'media'),
('General Motors', 'Traverse Suv', 'ligero_b', 'media'),
('General Motors', 'XT5 SUV', 'ligero_b', 'media'),
('General Motors', 'Xt4 Suv', 'ligero_b', 'media'),
('General Motors', 'Yukon Suv', 'ligero_b', 'media'),
('General Motors', 'Yukon XL', 'ligero_b', 'media'),
('Great Wall Motor', 'POER', 'ligero_b', 'media'),
('Great Wall Motor', 'POER 500', 'ligero_b', 'media'),
('Great Wall Motor', 'HAVAL H6', 'ligero_b', 'media'),
('Great Wall Motor', 'HAVAL Jolion', 'ligero_b', 'media'),
('Great Wall Motor', 'Ora 5', 'ligero_b', 'media'),
('Great Wall Motor', 'TANK 300', 'ligero_b', 'media'),
('Great Wall Motor', 'TANK 500', 'ligero_b', 'media'),
('Honda', 'Ridgeline', 'ligero_b', 'media'),
('Honda', 'CR-V-', 'ligero_b', 'media'),
('Honda', 'HR-V-', 'ligero_b', 'media'),
('Honda', 'CR-V', 'ligero_b', 'media'),
('Honda', 'CR-V-', 'ligero_b', 'media'),
('Honda', 'Honda Pilot', 'ligero_b', 'media'),
('Honda', 'BR-V', 'ligero_b', 'media'),
('Honda', 'BR-V', 'ligero_b', 'media'),
('Hyundai', 'Palisade', 'ligero_b', 'media'),
('Hyundai', 'Santa FE 7 P', 'ligero_b', 'media'),
('Hyundai', 'Santa Fe', 'ligero_b', 'media'),
('Hyundai', 'Creta', 'ligero_b', 'media'),
('Hyundai', 'IX35', 'ligero_b', 'media'),
('Hyundai', 'Tucson', 'ligero_b', 'media'),
('Infiniti', 'QX50', 'ligero_b', 'media'),
('Infiniti', 'QX55', 'ligero_b', 'media'),
('Infiniti', 'FX', 'ligero_b', 'media'),
('Infiniti', 'Infiniti Jx', 'ligero_b', 'media'),
('Infiniti', 'QX', 'ligero_b', 'media'),
('Infiniti', 'QX60', 'ligero_b', 'media'),
('Infiniti', 'QX70', 'ligero_b', 'media'),
('Infiniti', 'QX80', 'ligero_b', 'media'),
('Isuzu', 'ELF 200', 'ligero_b', 'media'),
('Isuzu', 'ELF 300', 'ligero_b', 'media'),
('Isuzu', 'ELF 350', 'ligero_b', 'media'),
('Isuzu', 'ELF100', 'ligero_b', 'media'),
('JAC', 'E Sei 1', 'ligero_b', 'media'),
('JAC', 'E Sei 2', 'ligero_b', 'media'),
('JAC', 'E Sei 4', 'ligero_b', 'media'),
('JAC', 'ESei4 Pro', 'ligero_b', 'media'),
('JAC', 'JAC2', 'ligero_b', 'media'),
('JAC', 'JAC4', 'ligero_b', 'media'),
('JAC', 'JAC6', 'ligero_b', 'media'),
('JAC', 'JAC8', 'ligero_b', 'media'),
('JAC', 'SEI7 PRO', 'ligero_b', 'media'),
('JAC', 'Sei2', 'ligero_b', 'media'),
('JAC', 'Sei3', 'ligero_b', 'media'),
('JAC', 'Sei4', 'ligero_b', 'media'),
('JAC', 'Sei4 Pro', 'ligero_b', 'media'),
('JAC', 'Sei6 Pro', 'ligero_b', 'media'),
('JAC', 'Sei7', 'ligero_b', 'media'),
('JAC', 'E Frison T8', 'ligero_b', 'media'),
('JAC', 'E X350', 'ligero_b', 'media'),
('JAC', 'EX450', 'ligero_b', 'media'),
('JAC', 'Frison', 'ligero_b', 'media'),
('JAC', 'GML X150 EV', 'ligero_b', 'media'),
('JAC', 'X 200', 'ligero_b', 'media'),
('JAC', 'X250', 'ligero_b', 'media'),
('JAC', 'X350', 'ligero_b', 'media'),
('JETOUR', 'Dashing', 'ligero_b', 'media'),
('JETOUR', 'T2', 'ligero_b', 'media'),
('JETOUR', 'X70', 'ligero_b', 'media'),
('JETOUR', 'X70 Plus', 'ligero_b', 'media'),
('Jetour Soueast', 'Dashing', 'ligero_b', 'media'),
('Jetour Soueast', 'G700 PHEV', 'ligero_b', 'media'),
('Jetour Soueast', 'S06 i-DM', 'ligero_b', 'media'),
('Jetour Soueast', 'S07', 'ligero_b', 'media'),
('Jetour Soueast', 'S08 i-DM', 'ligero_b', 'media'),
('Jetour Soueast', 'S09', 'ligero_b', 'media'),
('Jetour Soueast', 'T1', 'ligero_b', 'media'),
('Jetour Soueast', 'T1 i-DM', 'ligero_b', 'media'),
('Jetour Soueast', 'T2', 'ligero_b', 'media'),
('Jetour Soueast', 'T2 i-DM', 'ligero_b', 'media'),
('Jetour Soueast', 'X70', 'ligero_b', 'media'),
('Jetour Soueast', 'X70 Plus', 'ligero_b', 'media'),
('KIA', 'Tucson', 'ligero_b', 'media'),
('KIA', 'Seltos-', 'ligero_b', 'media'),
('KIA', 'Sonet', 'ligero_b', 'media'),
('KIA', 'EV6', 'ligero_b', 'media'),
('KIA', 'KIA Niro', 'ligero_b', 'media'),
('KIA', 'SPORTAGE', 'ligero_b', 'media'),
('KIA', 'Soul', 'ligero_b', 'media'),
('KIA', 'Sportage', 'ligero_b', 'media'),
('KIA', 'Sportage HEV', 'ligero_b', 'media'),
('KIA', 'Sorento', 'ligero_b', 'media'),
('KIA', 'Telluride', 'ligero_b', 'media'),
('KIA', 'Seltos', 'ligero_b', 'media'),
('Land Rover', 'Defender', 'ligero_b', 'media'),
('Land Rover', 'Evoque', 'ligero_b', 'media'),
('Land Rover', 'Freelander 2.5', 'ligero_b', 'media'),
('Land Rover', 'Lr2', 'ligero_b', 'media'),
('Land Rover', 'Lr3/Lr4', 'ligero_b', 'media'),
('Land Rover', 'Range Rover', 'ligero_b', 'media'),
('Land Rover', 'Range Rover Sport', 'ligero_b', 'media'),
('Leapmotor', 'B10', 'ligero_b', 'media'),
('Lexus', 'NX', 'ligero_b', 'media'),
('Lexus', 'RX', 'ligero_b', 'media'),
('Lexus', 'TX', 'ligero_b', 'media'),
('Lexus', 'GX', 'ligero_b', 'media'),
('Lexus', 'LX', 'ligero_b', 'media'),
('Lexus', 'UX', 'ligero_b', 'media'),
('Lincoln', 'Corsair', 'ligero_b', 'media'),
('Lincoln', 'AVIATOR', 'ligero_b', 'media'),
('Lincoln', 'Aviator Grand Touring', 'ligero_b', 'media'),
('Lincoln', 'MKC', 'ligero_b', 'media'),
('Lincoln', 'Mark Lt', 'ligero_b', 'media'),
('Mazda', 'CX-3', 'ligero_b', 'media'),
('Mazda', 'CX-30', 'ligero_b', 'media'),
('Mazda', 'CX-50', 'ligero_b', 'media'),
('Mazda', 'CX-3', 'ligero_b', 'media'),
('Mazda', 'CX-5', 'ligero_b', 'media'),
('Mazda', 'CX-70', 'ligero_b', 'media'),
('Mazda', 'CX-9', 'ligero_b', 'media'),
('Mazda', 'CX-90', 'ligero_b', 'media'),
('Mazda', 'Cx-7', 'ligero_b', 'media'),
('Mazda', 'BT-50', 'ligero_b', 'media'),
('Mercedes Benz', 'GLB', 'ligero_b', 'media'),
('Mercedes Benz', 'EQA', 'ligero_b', 'media'),
('Mercedes Benz', 'EQC', 'ligero_b', 'media'),
('Mercedes Benz', 'GLA', 'ligero_b', 'media'),
('Mercedes Benz', 'GLC', 'ligero_b', 'media'),
('Mercedes Benz', 'GLK 280', 'ligero_b', 'media'),
('Mercedes Benz', 'GLK 350', 'ligero_b', 'media'),
('Mercedes Benz', 'Gl 500', 'ligero_b', 'media'),
('Mercedes Benz', 'R 350', 'ligero_b', 'media'),
('Mercedes Benz', 'Sprinter', 'ligero_b', 'media'),
('Mercedes Benz', 'Vito Carga', 'ligero_b', 'media'),
('Mercedes Benz', 'Vito Pasaje', 'ligero_b', 'media'),
('Mercedes Benz', 'Clase G', 'ligero_b', 'media'),
('Mercedes Benz', 'G 500', 'ligero_b', 'media'),
('Mercedes Benz', 'Clase V', 'ligero_b', 'media'),
('Mercedes Benz', 'Vito', 'ligero_b', 'media'),
('Mercedes Benz', 'Clase GLE', 'ligero_b', 'media'),
('Mercedes Benz', 'Clase GLS', 'ligero_b', 'media'),
('Mercedes Benz', 'EQE SUV', 'ligero_b', 'media'),
('Mercedes Benz', 'EQS SUV', 'ligero_b', 'media'),
('Mercedes Benz', 'Gl 450', 'ligero_b', 'media'),
('Mercedes Benz', 'Ml 350', 'ligero_b', 'media'),
('Mercedes Benz', 'Ml 500', 'ligero_b', 'media'),
('Mercedes Benz', 'Ml 63 Amg', 'ligero_b', 'media'),
('Mercedes Benz', 'R 500', 'ligero_b', 'media'),
('Mercedes Benz', 'EQB', 'ligero_b', 'media'),
('Mercedes Benz', 'Cab Chassis', 'ligero_b', 'media'),
('Mercedes Benz', 'Cargo Van', 'ligero_b', 'media'),
('Mercedes Benz', 'Wagon', 'ligero_b', 'media'),
('MG Motor', 'HS', 'ligero_b', 'media'),
('MG Motor', 'HS PHEV', 'ligero_b', 'media'),
('MG Motor', 'HSHEV', 'ligero_b', 'media'),
('MG Motor', 'IMLS7', 'ligero_b', 'media'),
('MG Motor', 'MG One', 'ligero_b', 'media'),
('MG Motor', 'RX5', 'ligero_b', 'media'),
('MG Motor', 'RX8', 'ligero_b', 'media'),
('MG Motor', 'RX9', 'ligero_b', 'media'),
('MG Motor', 'ZS', 'ligero_b', 'media'),
('MG Motor', 'ZSEV', 'ligero_b', 'media'),
('MG Motor', 'ZSHEV', 'ligero_b', 'media'),
('MG Motor', 'eHS', 'ligero_b', 'media'),
('MG Motor', 'P9', 'ligero_b', 'media'),
('Mini', 'MINI COUNTRYMAN', 'ligero_b', 'media'),
('Mitsubishi', 'ASX', 'ligero_b', 'media'),
('Mitsubishi', 'Endeavor', 'ligero_b', 'media'),
('Mitsubishi', 'Outlander Sport', 'ligero_b', 'media'),
('Mitsubishi', 'Xpander', 'ligero_b', 'media'),
('Mitsubishi', 'Eclipse Cross', 'ligero_b', 'media'),
('Mitsubishi', 'Montero', 'ligero_b', 'media'),
('Mitsubishi', 'Montero Limited', 'ligero_b', 'media'),
('Mitsubishi', 'Outlander', 'ligero_b', 'media'),
('Mitsubishi', 'Outlander PHEV', 'ligero_b', 'media'),
('Mitsubishi', 'Montero Sport', 'ligero_b', 'media'),
('Mitsubishi', 'L200', 'ligero_b', 'media'),
('MOTORNATION', 'BAIC BJ20', 'ligero_b', 'media'),
('MOTORNATION', 'BAIC BJ40', 'ligero_b', 'media'),
('MOTORNATION', 'BAIC X30', 'ligero_b', 'media'),
('MOTORNATION', 'BAIC X55', 'ligero_b', 'media'),
('MOTORNATION', 'BAIC X65', 'ligero_b', 'media'),
('MOTORNATION', 'CHANGAN CS35PLUS', 'ligero_b', 'media'),
('MOTORNATION', 'CHANGAN CS55PLUS', 'ligero_b', 'media'),
('MOTORNATION', 'CHANGAN CS75PLUS', 'ligero_b', 'media'),
('MOTORNATION', 'CHANGAN UNI-K', 'ligero_b', 'media'),
('MOTORNATION', 'CHANGAN UNI-T', 'ligero_b', 'media'),
('MOTORNATION', 'DFSK 500', 'ligero_b', 'media'),
('MOTORNATION', 'DFSK 600', 'ligero_b', 'media'),
('MOTORNATION', 'DFSK E5', 'ligero_b', 'media'),
('MOTORNATION', 'GLORY 500', 'ligero_b', 'media'),
('MOTORNATION', 'SERES 5 EV', 'ligero_b', 'media'),
('MOTORNATION', 'T77', 'ligero_b', 'media'),
('MOTORNATION', 'BAIC X35', 'ligero_b', 'media'),
('MOTORNATION', 'CHANGAN HUNTER', 'ligero_b', 'media'),
('MOTORNATION', 'JMC GRAND AVENUE', 'ligero_b', 'media'),
('MOTORNATION', 'JMC VIGUS', 'ligero_b', 'media'),
('MOTORNATION', 'SERES 5 MAX', 'ligero_b', 'media'),
('MOTORNATION', 'STAR TRUCK', 'ligero_b', 'media'),
('Nissan', 'Kicks', 'ligero_b', 'media'),
('Nissan', 'NV 200 Cargo', 'ligero_b', 'media'),
('Nissan', 'NV 200 NY TAXI', 'ligero_b', 'media'),
('Nissan', 'KAIT', 'ligero_b', 'media'),
('Nissan', 'Armada', 'ligero_b', 'media'),
('Nissan', 'Xterra', 'ligero_b', 'media'),
('Nissan', 'Magnite', 'ligero_b', 'media'),
('Nissan', 'Murano', 'ligero_b', 'media'),
('Nissan', 'Pathfinder', 'ligero_b', 'media'),
('Nissan', 'Rogue', 'ligero_b', 'media'),
('Nissan', 'Urvan Panel', 'ligero_b', 'media'),
('Nissan', 'Urvan Panel Diesel', 'ligero_b', 'media'),
('Nissan', 'Urvan Pasajeros', 'ligero_b', 'media'),
('Nissan', 'Urvan Pasajeros Diesel', 'ligero_b', 'media'),
('Nissan', 'Xtrail', 'ligero_b', 'media'),
('Nissan', 'Chasis Largo', 'ligero_b', 'media'),
('Nissan', 'Chasis Largo Diesel', 'ligero_b', 'media'),
('Nissan', 'Estacas Largo', 'ligero_b', 'media'),
('Nissan', 'Frontier L4', 'ligero_b', 'media'),
('Nissan', 'NP300', 'ligero_b', 'media'),
('Nissan', 'Pickup Doble Cabina', 'ligero_b', 'media'),
('Nissan', 'Pickup Doble Cabina Diesel', 'ligero_b', 'media'),
('Nissan', 'Pickup King Cab STD', 'ligero_b', 'media'),
('Nissan', 'Pickup Largo', 'ligero_b', 'media'),
('Nissan', 'Pickup Largo Diesel', 'ligero_b', 'media'),
('Nissan', 'Frontier V4', 'ligero_b', 'media'),
('Nissan', 'Cabstar Mediano', 'ligero_b', 'media'),
('Nissan', 'Cabstar Small', 'ligero_b', 'media'),
('Nissan', 'Frontier V6', 'ligero_b', 'media'),
('Nissan', 'Titan', 'ligero_b', 'media'),
('Nissan', 'Frontier Diesel', 'ligero_b', 'media'),
('Omoda', 'C5', 'ligero_b', 'media'),
('Omoda', 'Jaecoo 7', 'ligero_b', 'media'),
('Peugeot', '2008', 'ligero_b', 'media'),
('Peugeot', '3008', 'ligero_b', 'media'),
('Peugeot', '5008', 'ligero_b', 'media'),
('Peugeot', 'LANDTREK', 'ligero_b', 'media'),
('Peugeot', 'Partner', 'ligero_b', 'media'),
('Peugeot', 'RIFTER', 'ligero_b', 'media'),
('Peugeot', 'Expert Cargo Van', 'ligero_b', 'media'),
('Peugeot', 'Expert Hdi', 'ligero_b', 'media'),
('Peugeot', 'Partner', 'ligero_b', 'media'),
('Peugeot', 'Partner Tepee Outdoor', 'ligero_b', 'media'),
('Peugeot', 'Manager Hdi', 'ligero_b', 'media'),
('Renault', 'Boreal', 'ligero_b', 'media'),
('Renault', 'Captur', 'ligero_b', 'media'),
('Renault', 'Duster', 'ligero_b', 'media'),
('Renault', 'Arkana', 'ligero_b', 'media'),
('Renault', 'Koleos', 'ligero_b', 'media'),
('Renault', 'Nueva Koleos', 'ligero_b', 'media'),
('Renault', 'Traffic Vu L2h2', 'ligero_b', 'media'),
('Renault', 'Traffic Carga', 'ligero_b', 'media'),
('Renault', 'Traffic Pasajeros', 'ligero_b', 'media'),
('Renault', 'Kangoo', 'ligero_b', 'media'),
('Renault', 'Kangoo Diesel', 'ligero_b', 'media'),
('Renault', 'Kangoo ZE', 'ligero_b', 'media'),
('Renault', 'Oroch', 'ligero_b', 'media'),
('SEAT', 'Tarraco', 'ligero_b', 'media'),
('SEAT', 'Arona', 'ligero_b', 'media'),
('SEAT', 'CUPRA Formentor', 'ligero_b', 'media'),
('SEAT', 'CUPRA Terramar', 'ligero_b', 'media'),
('SEAT', 'Ateca', 'ligero_b', 'media'),
('Subaru', 'B9 Tribeca', 'ligero_b', 'media'),
('Subaru', 'Crosstrek', 'ligero_b', 'media'),
('Subaru', 'Crosstrek MHEV', 'ligero_b', 'media'),
('Subaru', 'Forester', 'ligero_b', 'media'),
('Subaru', 'Forester e-BOXER HEV', 'ligero_b', 'media'),
('Subaru', 'Outback', 'ligero_b', 'media'),
('Subaru', 'Trailseeker', 'ligero_b', 'media'),
('Subaru', 'XV', 'ligero_b', 'media'),
('Suzuki', 'XL7', 'ligero_b', 'media'),
('Suzuki', 'S Cross', 'ligero_b', 'media'),
('Suzuki', 'Vitara', 'ligero_b', 'media'),
('Suzuki', 'FRONX', 'ligero_b', 'media'),
('Suzuki', 'Grand Vitara', 'ligero_b', 'media'),
('Suzuki', 'Grand Vitara', 'ligero_b', 'media'),
('Suzuki', 'Grand Vitara 4x4', 'ligero_b', 'media'),
('Suzuki', 'JIMNY', 'ligero_b', 'media'),
('Toyota', 'Rav4', 'ligero_b', 'media'),
('Toyota', 'Corolla Cross', 'ligero_b', 'media'),
('Toyota', 'Highlander', 'ligero_b', 'media'),
('Toyota', 'Rush', 'ligero_b', 'media'),
('Toyota', 'Sequoia', 'ligero_b', 'media'),
('Toyota', 'RAIZE', 'ligero_b', 'media'),
('Toyota', '4Runner', 'ligero_b', 'media'),
('Toyota', '4runner', 'ligero_b', 'media'),
('Toyota', 'Fjcruiser', 'ligero_b', 'media'),
('Toyota', 'Hiace P', 'ligero_b', 'media'),
('Toyota', 'Hiace V', 'ligero_b', 'media'),
('Toyota', 'Highlander', 'ligero_b', 'media'),
('Toyota', 'Lcruiser', 'ligero_b', 'media'),
('Toyota', 'Rav4', 'ligero_b', 'media'),
('Toyota', 'C-HR', 'ligero_b', 'media'),
('Toyota', 'Tacoma', 'ligero_b', 'media'),
('Toyota', 'Tacoma-', 'ligero_b', 'media'),
('Toyota', 'Tacoma', 'ligero_b', 'media'),
('Toyota', 'Tundra', 'ligero_b', 'media'),
('Toyota', 'Hilux Cc', 'ligero_b', 'media'),
('Toyota', 'Hilux Dc', 'ligero_b', 'media'),
('Toyota', 'Hilux Sc', 'ligero_b', 'media'),
('Volkswagen', 'Taos', 'ligero_b', 'media'),
('Volkswagen', 'Tiguan-', 'ligero_b', 'media'),
('Volkswagen', 'Eurovan Carga', 'ligero_b', 'media'),
('Volkswagen', 'Eurovan Pasajeros', 'ligero_b', 'media'),
('Volkswagen', 'Tiguan', 'ligero_b', 'media'),
('Volkswagen', 'Transporter Carga', 'ligero_b', 'media'),
('Volkswagen', 'Transporter Pasajeros', 'ligero_b', 'media'),
('Volkswagen', 'Nivus', 'ligero_b', 'media'),
('Volkswagen', 'T-Cross', 'ligero_b', 'media'),
('Volkswagen', 'Touareg', 'ligero_b', 'media'),
('Volkswagen', 'Cross Sport', 'ligero_b', 'media'),
('Volkswagen', 'ID.4', 'ligero_b', 'media'),
('Volkswagen', 'Teramont', 'ligero_b', 'media'),
('Volkswagen', 'T-Cross', 'ligero_b', 'media'),
('Volkswagen', 'Taigun', 'ligero_b', 'media'),
('Volkswagen', 'Crafter chasis', 'ligero_b', 'media'),
('Volkswagen', 'e-Crafter', 'ligero_b', 'media'),
('Volkswagen', 'Crafter', 'ligero_b', 'media'),
('Volkswagen', 'Amarok', 'ligero_b', 'media'),
('Volkswagen', 'Vw Van', 'ligero_b', 'media'),
('Volkswagen', 'Pointer Pick Up', 'ligero_b', 'media'),
('Volkswagen', 'Saveiro', 'ligero_b', 'media'),
('Volkswagen', 'Volkswagen Caddy', 'ligero_b', 'media'),
('Volvo', 'XC60', 'ligero_b', 'media'),
('Volvo', 'EX30', 'ligero_b', 'media'),
('Volvo', 'EX90', 'ligero_b', 'media'),
('Volvo', 'XC60 II', 'ligero_b', 'media'),
('Volvo', 'XC90 3.2', 'ligero_b', 'media'),
('Volvo', 'XC90 II', 'ligero_b', 'media'),
('Volvo', 'XC90 V8', 'ligero_b', 'media'),
('Volvo', 'Xc70 2.5t', 'ligero_b', 'media'),
('Volvo', 'Xc90', 'ligero_b', 'media'),
('Volvo', 'Xc90 T6', 'ligero_b', 'media'),
('Porsche', 'Cayman', 'ligero_a', 'premium'),
('Porsche', '718 Boxster', 'ligero_a', 'premium'),
('Porsche', '911 Carrera', 'ligero_a', 'premium'),
('Porsche', '911 Carrera / Turbo / GT', 'ligero_a', 'premium'),
('Porsche', '911 Turbo', 'ligero_a', 'premium'),
('Porsche', 'Boxster', 'ligero_a', 'premium'),
('Porsche', 'Gt3 / Gt2 / Carrera Gt', 'ligero_a', 'premium'),
('Acura', 'NSX', 'ligero_a', 'premium'),
('Ford Motor', 'Mustang', 'ligero_a', 'premium'),
('General Motors', 'Camaro Convertible', 'ligero_a', 'premium'),
('General Motors', 'Camaro Convertible', 'ligero_a', 'premium'),
('General Motors', 'Corvette 2 Pts. Convertible', 'ligero_a', 'premium'),
('General Motors', 'Camaro', 'ligero_a', 'premium'),
('General Motors', 'Camaro', 'ligero_a', 'premium'),
('General Motors', 'Corvette', 'ligero_a', 'premium'),
('Mercedes Benz', 'AMG GT', 'ligero_a', 'premium'),
('Nissan', 'GT-R', 'ligero_a', 'premium'),
('Toyota', 'GR Supra', 'ligero_a', 'premium');


-- Autoasigna categoría de tarifa + gama por marca/modelo. Devuelve null en
-- ambas columnas cuando no hay match o cuando el marca/modelo tiene más de
-- una combinación distinta en el catálogo fuente (ambigüedad real del Excel,
-- no se fuerza un dato incorrecto -- igual que tipoSugeridoParaVehiculo en TS).
create or replace function public.catalogar_vehiculo_para_tarifa(p_marca text, p_modelo text)
returns table(categoria_tarifa public.categoria_tarifa_vehiculo, gama public.gama_vehiculo)
language sql stable as $$
  with combinaciones as (
    select distinct c.categoria_tarifa, c.gama
    from public.catalogo_vehiculos_tarifa c
    where lower(unaccent(c.marca)) = lower(unaccent(p_marca))
      and lower(unaccent(c.modelo)) = lower(unaccent(p_modelo))
  )
  select combinaciones.categoria_tarifa, combinaciones.gama
  from combinaciones
  where (select count(*) from combinaciones) = 1;
$$;

revoke all on function public.catalogar_vehiculo_para_tarifa(text, text) from public;
grant execute on function public.catalogar_vehiculo_para_tarifa(text, text) to authenticated;

-- Previsualización de tarifa (sin crear traslado): la usa el último paso del
-- wizard de app-usuario, ya con destino y fecha/hora capturados, para que el
-- usuario LEA la tarifa que va a pagar antes de confirmar la solicitud -- no
-- se le pide presupuesto en ningún punto del flujo.
--
-- p_fecha_hora null = "lo antes posible" -> se usa now() para horario/día,
-- igual que admin_sugerir_tarifa_traslado.
create or replace function public.usuario_previsualizar_tarifa(
  p_marca text,
  p_modelo text,
  p_distancia_km numeric,
  p_tiempo_estimado_horas numeric,
  p_fecha_hora timestamptz
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_usuario_id uuid;
  v_categoria public.categoria_tarifa_vehiculo;
  v_gama public.gama_vehiculo;
  v_condicion public.condicion_vehiculo := 'seminueva';
  v_momento timestamptz := coalesce(p_fecha_hora, now());
  v_rango public.rango_distancia;
  v_horario public.horario_traslado;
  v_dia public.dia_traslado;
  v_tarifa numeric;
begin
  select id into v_usuario_id from public.usuarios where auth_user_id = auth.uid();
  if v_usuario_id is null then raise exception 'Usuario no encontrado'; end if;

  if p_distancia_km is null or p_distancia_km < 0 then raise exception 'Distancia inválida'; end if;
  if p_tiempo_estimado_horas is null or p_tiempo_estimado_horas < 0 then raise exception 'Tiempo inválido'; end if;

  select categoria_tarifa, gama into v_categoria, v_gama
  from public.catalogar_vehiculo_para_tarifa(p_marca, p_modelo);

  if v_categoria is null or v_gama is null then
    return jsonb_build_object(
      'disponible', false,
      'motivo', 'Este vehículo no está en el catálogo de clasificación automática; Torre de Control te enviará la cotización manualmente.'
    );
  end if;

  v_rango := public.rango_desde_distancia(p_distancia_km);
  v_horario := public.horario_desde_timestamp(v_momento);
  v_dia := public.dia_desde_timestamp(v_momento);

  v_tarifa := public.calcular_tarifa_traslado(
    v_categoria, v_rango, v_gama, v_condicion, v_horario, v_dia, p_distancia_km, p_tiempo_estimado_horas
  );

  return jsonb_build_object(
    'disponible', true,
    'tarifa', v_tarifa,
    'categoria_tarifa', v_categoria,
    'gama', v_gama,
    'condicion', v_condicion,
    'horario', v_horario,
    'dia', v_dia
  );
end; $$;

revoke all on function public.usuario_previsualizar_tarifa(text, text, numeric, numeric, timestamptz) from public;
grant execute on function public.usuario_previsualizar_tarifa(text, text, numeric, numeric, timestamptz) to authenticated;

-- Reemplaza usuario_crea_traslado (20260713000128):
--  - ya no acepta/usa presupuesto_usuario como precio -- se ignora si llega.
--  - autoasigna categoria_tarifa/gama (catálogo) y usa la condicion declarada
--    por el usuario a un vehículo nuevo en el momento de crearlo.
--  - si el vehículo (nuevo o reutilizado) tiene clasificación disponible,
--    calcula precio_cotizado automáticamente con la fórmula vigente y dispara
--    el estado a 'cotizacion_generada' -- el usuario ya lee su tarifa desde
--    el mismo momento en que confirma la solicitud, sin esperar a un admin.
--  - si no hay clasificación (vehículo fuera de catálogo o ambiguo), la
--    solicitud se crea igual pero precio_cotizado queda null y el estado se
--    queda en 'solicitud_creada', como antes, para que Torre de Control
--    cotice a mano.
create or replace function public.usuario_crea_traslado(
  p_vehiculo_id uuid,
  p_vehiculo jsonb,
  p_traslado jsonb,
  p_clave_idempotencia uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usuario_id uuid;
  v_estado_verificacion public.estado_verificacion;
  v_tipo_pago public.tipo_pago;
  v_vehiculo_id uuid;
  v_tipo_vehiculo public.tipo_vehiculo;
  v_traslado_id uuid;
  v_anio int;
  v_anio_maximo int := extract(year from now())::int + 1;
  v_modalidad text;
  v_fecha_programada timestamptz;
  v_tiene_tarjeta boolean;
  v_tiene_verificacion boolean;
  v_tiene_placas boolean;
  v_puede_circular boolean;
  v_distancia_km numeric;
  v_tiempo_estimado_horas numeric;
  v_categoria_tarifa public.categoria_tarifa_vehiculo;
  v_gama public.gama_vehiculo;
  v_condicion public.condicion_vehiculo;
  v_precio_cotizado numeric;
  v_estado_inicial public.estado_traslado := 'solicitud_creada';
  v_momento timestamptz;
begin
  select id, estado_verificacion
  into v_usuario_id, v_estado_verificacion
  from public.usuarios
  where auth_user_id = auth.uid();
  if v_usuario_id is null then
    raise exception 'Usuario no encontrado';
  end if;

  if v_estado_verificacion <> 'verificado' then
    raise exception 'Tu cuenta debe estar verificada para solicitar un traslado';
  end if;

  if p_clave_idempotencia is null then raise exception 'La clave de idempotencia es obligatoria'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_usuario_id::text || p_clave_idempotencia::text, 0));
  select id, tipo_pago into v_traslado_id, v_tipo_pago
  from public.traslados where usuario_id = v_usuario_id and clave_idempotencia = p_clave_idempotencia;
  if v_traslado_id is not null then
    return jsonb_build_object('id', v_traslado_id, 'tipo_pago', v_tipo_pago);
  end if;

  v_tipo_pago := public.determinar_tipo_pago_usuario(v_usuario_id);
  v_modalidad := p_traslado->>'modalidad_programacion';
  if v_modalidad not in ('lo_antes_posible', 'programado') then raise exception 'Modalidad de programación inválida'; end if;
  v_fecha_programada := nullif(p_traslado->>'fecha_hora_programada', '')::timestamptz;
  if v_modalidad = 'programado' then
    if v_fecha_programada is null then raise exception 'La fecha programada es obligatoria'; end if;
    if v_fecha_programada < now() + interval '2 hours' then raise exception 'La fecha no cumple con la anticipación mínima de 2 horas'; end if;
  elsif v_fecha_programada is not null then
    raise exception 'La modalidad inmediata no admite fecha programada';
  end if;

  if p_vehiculo_id is not null then
    select id, tipo, tiene_tarjeta_circulacion, tiene_verificacion, tiene_placas, puede_circular_rodando,
           categoria_tarifa, gama, condicion
    into v_vehiculo_id, v_tipo_vehiculo, v_tiene_tarjeta, v_tiene_verificacion, v_tiene_placas, v_puede_circular,
         v_categoria_tarifa, v_gama, v_condicion
    from public.vehiculos
    where id = p_vehiculo_id
      and usuario_id = v_usuario_id;

    if v_vehiculo_id is null then
      raise exception 'El vehículo indicado no existe o no pertenece al usuario.';
    end if;
  else
    if p_vehiculo is null then
      raise exception 'Debes indicar un vehículo guardado (p_vehiculo_id) o los datos de un vehículo nuevo (p_vehiculo).';
    end if;

    v_anio := (p_vehiculo->>'anio')::int;
    if v_anio is null or v_anio < 1980 or v_anio > v_anio_maximo then
      raise exception 'El año del vehículo debe ser un número entre 1980 y %.', v_anio_maximo;
    end if;

    v_tipo_vehiculo := (p_vehiculo->>'tipo')::public.tipo_vehiculo;
    v_tiene_tarjeta := coalesce((p_vehiculo->>'tiene_tarjeta_circulacion')::boolean, false);
    v_tiene_verificacion := coalesce((p_vehiculo->>'tiene_verificacion')::boolean, false);
    v_tiene_placas := coalesce((p_vehiculo->>'tiene_placas')::boolean, false);
    v_puede_circular := coalesce((p_vehiculo->>'puede_circular_rodando')::boolean, false);

    -- Autoasignación (RT-13): categoría/gama por catálogo marca+modelo.
    -- La condición la declara el usuario en el formulario; Torre de Control
    -- puede corregirla después si detecta algo distinto durante la
    -- verificación física.
    select categoria_tarifa, gama into v_categoria_tarifa, v_gama
    from public.catalogar_vehiculo_para_tarifa(p_vehiculo->>'marca', p_vehiculo->>'modelo');
    v_condicion := coalesce(nullif(p_vehiculo->>'condicion', '')::public.condicion_vehiculo, 'seminueva');

    insert into public.vehiculos (
      usuario_id, tipo, transmision, marca, modelo, anio, color, placas, vin,
      estado_general_declarado, tiene_tarjeta_circulacion, tiene_verificacion,
      tiene_placas, puede_circular_rodando, categoria_tarifa, gama, condicion
    ) values (
      v_usuario_id,
      v_tipo_vehiculo,
      p_vehiculo->>'transmision',
      p_vehiculo->>'marca',
      p_vehiculo->>'modelo',
      v_anio,
      p_vehiculo->>'color',
      p_vehiculo->>'placas',
      p_vehiculo->>'vin',
      p_vehiculo->>'estado_general_declarado',
      coalesce((p_vehiculo->>'tiene_tarjeta_circulacion')::boolean, false),
      coalesce((p_vehiculo->>'tiene_verificacion')::boolean, false),
      coalesce((p_vehiculo->>'tiene_placas')::boolean, false),
      coalesce((p_vehiculo->>'puede_circular_rodando')::boolean, false),
      v_categoria_tarifa,
      v_gama,
      v_condicion
    )
    returning id into v_vehiculo_id;
  end if;

  if not (v_tiene_tarjeta and v_tiene_verificacion and v_tiene_placas and v_puede_circular) then
    raise exception 'El MVP solo admite vehículos que encienden, tienen documentación vigente y pueden circular rodando';
  end if;

  v_distancia_km := nullif(p_traslado->>'distancia_km', '')::numeric;
  v_tiempo_estimado_horas := nullif(p_traslado->>'tiempo_estimado_horas', '')::numeric;
  if (v_distancia_km is null) <> (v_tiempo_estimado_horas is null) then
    raise exception 'La distancia y el tiempo estimado de ruta deben enviarse juntos.';
  end if;
  if v_distancia_km is not null and (v_distancia_km < 0 or v_distancia_km > 20000) then
    raise exception 'La distancia estimada de ruta es inválida.';
  end if;
  if v_tiempo_estimado_horas is not null and (v_tiempo_estimado_horas < 0 or v_tiempo_estimado_horas > 720) then
    raise exception 'El tiempo estimado de ruta es inválido.';
  end if;

  -- Tarifa automática (RT-13): si el vehículo ya tiene categoría/gama/condición
  -- y llegó distancia/tiempo de Mapbox, se calcula y se guarda de una vez --
  -- el usuario no espera a que un admin le teclee un precio.
  if v_categoria_tarifa is not null and v_gama is not null and v_condicion is not null
     and v_distancia_km is not null and v_tiempo_estimado_horas is not null then
    v_momento := coalesce(v_fecha_programada, now());
    v_precio_cotizado := public.calcular_tarifa_traslado(
      v_categoria_tarifa, public.rango_desde_distancia(v_distancia_km), v_gama, v_condicion,
      public.horario_desde_timestamp(v_momento), public.dia_desde_timestamp(v_momento),
      v_distancia_km, v_tiempo_estimado_horas
    );
    v_estado_inicial := 'cotizacion_generada';
  end if;

  insert into public.traslados (
    usuario_id, vehiculo_id, estado,
    contacto_entrega_nombre, contacto_entrega_telefono,
    contacto_recepcion_nombre, contacto_recepcion_telefono,
    origen_lat, origen_lng, origen_direccion, origen_ciudad, origen_referencias,
    destino_lat, destino_lng, destino_direccion, destino_ciudad, destino_referencias,
    instrucciones_especiales, modalidad_programacion, fecha_hora_programada,
    tipo_ruta, ventana_recoleccion, ventana_entrega, tipo_servicio, motivo_servicio,
    presupuesto_usuario, precio_cotizado, precio_final, tipo_pago, clave_idempotencia,
    distancia_km, tiempo_estimado_horas,
    cotizacion_expira_en
  ) values (
    v_usuario_id, v_vehiculo_id, v_estado_inicial,
    p_traslado->>'contacto_entrega_nombre',
    p_traslado->>'contacto_entrega_telefono',
    p_traslado->>'contacto_recepcion_nombre',
    p_traslado->>'contacto_recepcion_telefono',
    nullif(p_traslado->>'origen_lat', '')::numeric,
    nullif(p_traslado->>'origen_lng', '')::numeric,
    p_traslado->>'origen_direccion',
    p_traslado->>'origen_ciudad',
    p_traslado->>'origen_referencias',
    nullif(p_traslado->>'destino_lat', '')::numeric,
    nullif(p_traslado->>'destino_lng', '')::numeric,
    p_traslado->>'destino_direccion',
    p_traslado->>'destino_ciudad',
    p_traslado->>'destino_referencias',
    p_traslado->>'instrucciones_especiales',
    p_traslado->>'modalidad_programacion',
    v_fecha_programada,
    p_traslado->>'tipo_ruta',
    p_traslado->>'ventana_recoleccion',
    p_traslado->>'ventana_entrega',
    p_traslado->>'tipo_servicio',
    p_traslado->>'motivo_servicio',
    null, v_precio_cotizado, null, v_tipo_pago, p_clave_idempotencia,
    v_distancia_km, v_tiempo_estimado_horas,
    case when v_precio_cotizado is not null then now() + interval '72 hours' else null end
  )
  returning id into v_traslado_id;

  insert into public.registro_auditoria (traslado_id, evento, actor, actor_id, datos)
  values (
    v_traslado_id,
    'creacion_solicitud_traslado',
    'usuario',
    v_usuario_id,
    jsonb_build_object(
      'vehiculo_id', v_vehiculo_id,
      'vehiculo_reutilizado', p_vehiculo_id is not null,
      'tipo_pago', v_tipo_pago,
      'distancia_km', v_distancia_km,
      'tiempo_estimado_horas', v_tiempo_estimado_horas,
      'precio_cotizado_automatico', v_precio_cotizado
    )
  );

  return jsonb_build_object('id', v_traslado_id, 'tipo_pago', v_tipo_pago, 'precio_cotizado', v_precio_cotizado);
end;
$$;

revoke all on function public.usuario_crea_traslado(uuid, jsonb, jsonb, uuid) from public;
grant execute on function public.usuario_crea_traslado(uuid, jsonb, jsonb, uuid) to authenticated;

comment on column public.traslados.presupuesto_usuario is
  'OBSOLETO (RT-13): el flujo ya no le pide presupuesto al usuario, la tarifa es calculada por el sistema. Columna conservada solo por compatibilidad histórica con traslados creados antes de RT-13; usuario_crea_traslado ya no la escribe.';

notify pgrst, 'reload schema';
