import type { EstadoTraslado } from "../types/traslado";
import { GLOSARIO_OPERATIVO } from "../constants/glosario-operativo";

// PRD §6 — los 34 estados del traslado, en el orden en que aparecen en la tabla — FUENTE DE VERDAD PR-14
// Inventario: 34 estados (reconcilia histórico 28, informe 32, catálogo 34). Código manda; docs se regeneran desde aquí.
export const ESTADOS_TRASLADO: EstadoTraslado[] = [
  "usuario_pendiente_verificacion",
  "usuario_verificado",
  "solicitud_creada",
  "documentacion_pendiente",
  "documentacion_en_revision",
  "documentacion_validada",
  "cotizacion_generada",
  "cotizacion_aceptada",
  "servicio_confirmado",
  "pendiente_de_conductor",
  "conductor_asignado",
  "conductor_en_camino_al_origen",
  "conductor_en_punto_de_recoleccion",
  "verificacion_vehiculo_en_proceso",
  "evidencia_inicial_en_proceso",
  "evidencia_inicial_completada",
  "vehiculo_recibido",
  "traslado_en_curso",
  "incidencia_reportada",
  "llegada_a_destino",
  "evidencia_final_en_proceso",
  "evidencia_final_completada",
  "entrega_confirmada",
  "pago_pendiente",
  "pago_completado",
  "servicio_cerrado",
  "servicio_cancelado",
  "traslado_fallido",
  "dano_no_reportado_en_revision",
  "reclamo_abierto",
  "reclamo_resuelto",
  "cierre_operativo_con_incidencia_abierta",
  "disputa_abierta",
  "disputa_resuelta"
];

export const ETIQUETA_ESTADO_TRASLADO: Record<EstadoTraslado, string> = {
  usuario_pendiente_verificacion: "Usuario pendiente de verificación",
  usuario_verificado: "Usuario verificado",
  solicitud_creada: GLOSARIO_OPERATIVO.solicitado,
  documentacion_pendiente: "Documentación pendiente",
  documentacion_en_revision: "Documentación en revisión",
  documentacion_validada: "Documentación validada",
  cotizacion_generada: "Cotización generada",
  cotizacion_aceptada: "Cotización lista",
  servicio_confirmado: GLOSARIO_OPERATIVO.aceptado,
  pendiente_de_conductor: GLOSARIO_OPERATIVO.solicitado,
  conductor_asignado: GLOSARIO_OPERATIVO.aceptado,
  conductor_en_camino_al_origen: "Conductor en camino al origen",
  conductor_en_punto_de_recoleccion: "Conductor en punto de recolección",
  verificacion_vehiculo_en_proceso: `${GLOSARIO_OPERATIVO.evidencia} en curso`,
  evidencia_inicial_en_proceso: `${GLOSARIO_OPERATIVO.evidencia} en curso`,
  evidencia_inicial_completada: `${GLOSARIO_OPERATIVO.evidencia} inicial completo`,
  vehiculo_recibido: "Vehículo recibido",
  traslado_en_curso: GLOSARIO_OPERATIVO.en_progreso,
  incidencia_reportada: "Problema reportado",
  llegada_a_destino: "Llegada a destino",
  evidencia_final_en_proceso: `${GLOSARIO_OPERATIVO.evidencia} final en curso`,
  evidencia_final_completada: `${GLOSARIO_OPERATIVO.evidencia} final completo`,
  entrega_confirmada: "Entrega confirmada",
  pago_pendiente: GLOSARIO_OPERATIVO.payout_pending,
  pago_completado: "Pago completado",
  servicio_cerrado: "Servicio cerrado",
  servicio_cancelado: "Servicio cancelado",
  traslado_fallido: "Traslado fallido",
  dano_no_reportado_en_revision: "Daño en validación",
  reclamo_abierto: "Reclamo abierto",
  reclamo_resuelto: "Reclamo resuelto",
  cierre_operativo_con_incidencia_abierta: "Cierre con problema reportado",
  disputa_abierta: `${GLOSARIO_OPERATIVO.disputa} en curso`,
  disputa_resuelta: `${GLOSARIO_OPERATIVO.disputa} resuelta`
};
